[package]
name = "oxide-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "oxide-client"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
oxide-render.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
winit.workspace = true
