[package]
name = "oxide-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "oxide-client"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
