//! The creative data: the damage sub-items every variant registration populates,
//! the ordered list of each creative tab, and the potion registry's names.
//!
//! Derived from the MCP-919 reference tree (never copied): the sub-item sets from
//! the `getSubItems`/`getSubBlocks` overrides of the item and block classes, the
//! order from the registry's own id iteration (`Item.itemRegistry` iterates
//! `ObjectIntIdentityMap`'s id list, `util/ObjectIntIdentityMap.java`:38-41, so
//! ascending by id) filtered by each item's `getCreativeTab`, the search tab's
//! list from `GuiContainerCreative.updateCreativeSearch` (`:341-386`), the potion
//! set from `ItemPotion.getSubItems` (`item/ItemPotion.java`:339-394) over the 1.8
//! damage encoding (`potion/PotionHelper.java`:386-450), the tabs from
//! `creativetab/CreativeTabs.java`, and the display strings from the en_US language
//! file (which the repository never carries; only the strings it defines are
//! committed). The per-class derivations are recorded in `refs/m5-task-9/derive.py`
//! and pinned by the tests.

use super::{CreativeTab, PotionName, SubItem, TabEntry, TabMeta};

/// Each tab's own data (`CreativeTabs`'s anonymous subclasses), in
/// `creativeTabArray` order.
pub(super) static TAB_META: [TabMeta; 12] = [
    TabMeta {
        index: 0,
        label: "buildingBlocks",
        icon: TabEntry { id: 45, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 1,
        label: "decorations",
        icon: TabEntry { id: 175, damage: 5 },
        sheet: "items.png",
    },
    TabMeta {
        index: 2,
        label: "redstone",
        icon: TabEntry { id: 331, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 3,
        label: "transportation",
        icon: TabEntry { id: 27, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 4,
        label: "misc",
        icon: TabEntry { id: 327, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 5,
        label: "search",
        icon: TabEntry { id: 345, damage: 0 },
        sheet: "item_search.png",
    },
    TabMeta {
        index: 6,
        label: "food",
        icon: TabEntry { id: 260, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 7,
        label: "tools",
        icon: TabEntry { id: 258, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 8,
        label: "combat",
        icon: TabEntry { id: 283, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 9,
        label: "brewing",
        icon: TabEntry { id: 373, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 10,
        label: "materials",
        icon: TabEntry { id: 280, damage: 0 },
        sheet: "items.png",
    },
    TabMeta {
        index: 11,
        label: "inventory",
        icon: TabEntry { id: 54, damage: 0 },
        sheet: "inventory.png",
    },
];

/// (item id, first index into [`SUB_ITEMS`], count) per variant registration,
/// ascending by id.
pub(super) static SUB_ITEM_RANGES: [(i16, usize, usize); 39] = [
    (1, 0, 7),
    (3, 7, 3),
    (5, 10, 6),
    (6, 16, 6),
    (12, 22, 2),
    (17, 24, 4),
    (18, 28, 4),
    (19, 32, 2),
    (24, 34, 3),
    (31, 37, 2),
    (35, 39, 16),
    (37, 55, 1),
    (38, 56, 9),
    (44, 65, 7),
    (95, 72, 16),
    (97, 88, 6),
    (98, 94, 4),
    (126, 98, 6),
    (139, 104, 2),
    (145, 106, 3),
    (155, 109, 3),
    (159, 112, 16),
    (160, 128, 16),
    (161, 144, 2),
    (162, 146, 2),
    (168, 148, 3),
    (171, 151, 16),
    (175, 167, 6),
    (179, 173, 3),
    (182, 176, 1),
    (263, 177, 2),
    (322, 179, 2),
    (349, 181, 4),
    (350, 185, 2),
    (351, 187, 16),
    (373, 203, 63),
    (383, 266, 27),
    (397, 293, 5),
    (425, 298, 16),
];

/// The sub-items themselves, in each registration's populate order.
pub(super) static SUB_ITEMS: [SubItem; 314] = [
    SubItem {
        damage: 0,
        name: "Stone",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Granite",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Polished Granite",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Diorite",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 4,
        name: "Polished Diorite",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 5,
        name: "Andesite",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 6,
        name: "Polished Andesite",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Dirt",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Coarse Dirt",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Podzol",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Oak Wood Planks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Spruce Wood Planks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Birch Wood Planks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Jungle Wood Planks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 4,
        name: "Acacia Wood Planks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 5,
        name: "Dark Oak Wood Planks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Oak Sapling",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Spruce Sapling",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Birch Sapling",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Jungle Sapling",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Acacia Sapling",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 5,
        name: "Dark Oak Sapling",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Sand",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Red Sand",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Oak Wood",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Spruce Wood",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Birch Wood",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Jungle Wood",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Oak Leaves",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Spruce Leaves",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Birch Leaves",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Jungle Leaves",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Sponge",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Wet Sponge",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Sandstone",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Chiseled Sandstone",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Smooth Sandstone",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Grass",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Fern",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Orange Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Magenta Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Light Blue Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 4,
        name: "Yellow Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 5,
        name: "Lime Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 6,
        name: "Pink Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 7,
        name: "Gray Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 8,
        name: "Light Gray Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 9,
        name: "Cyan Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 10,
        name: "Purple Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 11,
        name: "Blue Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 12,
        name: "Brown Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 13,
        name: "Green Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 14,
        name: "Red Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 15,
        name: "Black Wool",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Dandelion",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Poppy",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Blue Orchid",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Allium",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Azure Bluet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Red Tulip",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 5,
        name: "Orange Tulip",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 6,
        name: "White Tulip",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 7,
        name: "Pink Tulip",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 8,
        name: "Oxeye Daisy",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Stone Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Sandstone Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Cobblestone Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 4,
        name: "Bricks Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 5,
        name: "Stone Bricks Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 6,
        name: "Nether Brick Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 7,
        name: "Quartz Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "White Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Orange Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Magenta Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Light Blue Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 4,
        name: "Yellow Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 5,
        name: "Lime Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 6,
        name: "Pink Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 7,
        name: "Gray Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 8,
        name: "Light Gray Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 9,
        name: "Cyan Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 10,
        name: "Purple Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 11,
        name: "Blue Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 12,
        name: "Brown Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 13,
        name: "Green Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 14,
        name: "Red Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 15,
        name: "Black Stained Glass",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Stone Monster Egg",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Cobblestone Monster Egg",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Stone Brick Monster Egg",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Mossy Stone Brick Monster Egg",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Cracked Stone Brick Monster Egg",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 5,
        name: "Chiseled Stone Brick Monster Egg",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Stone Bricks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Mossy Stone Bricks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Cracked Stone Bricks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Chiseled Stone Bricks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Oak Wood Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Spruce Wood Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Birch Wood Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Jungle Wood Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 4,
        name: "Acacia Wood Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 5,
        name: "Dark Oak Wood Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Cobblestone Wall",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Mossy Cobblestone Wall",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Anvil",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Slightly Damaged Anvil",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Very Damaged Anvil",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Block of Quartz",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Chiseled Quartz Block",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Pillar Quartz Block",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "White Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Orange Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Magenta Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 3,
        name: "Light Blue Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 4,
        name: "Yellow Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 5,
        name: "Lime Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 6,
        name: "Pink Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 7,
        name: "Gray Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 8,
        name: "Light Gray Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 9,
        name: "Cyan Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 10,
        name: "Purple Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 11,
        name: "Blue Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 12,
        name: "Brown Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 13,
        name: "Green Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 14,
        name: "Red Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 15,
        name: "Black Stained Clay",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "White Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Orange Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Magenta Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Light Blue Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Yellow Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 5,
        name: "Lime Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 6,
        name: "Pink Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 7,
        name: "Gray Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 8,
        name: "Light Gray Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 9,
        name: "Cyan Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 10,
        name: "Purple Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 11,
        name: "Blue Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 12,
        name: "Brown Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 13,
        name: "Green Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 14,
        name: "Red Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 15,
        name: "Black Stained Glass Pane",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Acacia Leaves",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 5,
        name: "Dark Oak Leaves",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Acacia Wood",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 5,
        name: "Dark Oak Wood",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Prismarine",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Prismarine Bricks",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Dark Prismarine",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Orange Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Magenta Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Light Blue Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Yellow Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 5,
        name: "Lime Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 6,
        name: "Pink Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 7,
        name: "Gray Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 8,
        name: "Light Gray Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 9,
        name: "Cyan Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 10,
        name: "Purple Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 11,
        name: "Blue Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 12,
        name: "Brown Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 13,
        name: "Green Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 14,
        name: "Red Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 15,
        name: "Black Carpet",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Sunflower",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Lilac",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Double Tallgrass",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Large Fern",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Rose Bush",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 5,
        name: "Peony",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Red Sandstone",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 1,
        name: "Chiseled Red Sandstone",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 2,
        name: "Smooth Red Sandstone",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Red Sandstone Slab",
        tab: CreativeTab::BuildingBlocks,
    },
    SubItem {
        damage: 0,
        name: "Coal",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 1,
        name: "Charcoal",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 0,
        name: "Golden Apple",
        tab: CreativeTab::Food,
    },
    SubItem {
        damage: 1,
        name: "Golden Apple",
        tab: CreativeTab::Food,
    },
    SubItem {
        damage: 0,
        name: "Raw Fish",
        tab: CreativeTab::Food,
    },
    SubItem {
        damage: 1,
        name: "Raw Salmon",
        tab: CreativeTab::Food,
    },
    SubItem {
        damage: 2,
        name: "Clownfish",
        tab: CreativeTab::Food,
    },
    SubItem {
        damage: 3,
        name: "Pufferfish",
        tab: CreativeTab::Food,
    },
    SubItem {
        damage: 0,
        name: "Cooked Fish",
        tab: CreativeTab::Food,
    },
    SubItem {
        damage: 1,
        name: "Cooked Salmon",
        tab: CreativeTab::Food,
    },
    SubItem {
        damage: 0,
        name: "Ink Sac",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 1,
        name: "Rose Red",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 2,
        name: "Cactus Green",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 3,
        name: "Cocoa Beans",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 4,
        name: "Lapis Lazuli",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 5,
        name: "Purple Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 6,
        name: "Cyan Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 7,
        name: "Light Gray Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 8,
        name: "Gray Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 9,
        name: "Pink Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 10,
        name: "Lime Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 11,
        name: "Dandelion Yellow",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 12,
        name: "Light Blue Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 13,
        name: "Magenta Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 14,
        name: "Orange Dye",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 15,
        name: "Bone Meal",
        tab: CreativeTab::Materials,
    },
    SubItem {
        damage: 0,
        name: "Water Bottle",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8193,
        name: "Potion of Regeneration",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8225,
        name: "Potion of Regeneration",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8257,
        name: "Potion of Regeneration",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16385,
        name: "Splash Potion of Regeneration",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16417,
        name: "Splash Potion of Regeneration",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16449,
        name: "Splash Potion of Regeneration",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8194,
        name: "Potion of Swiftness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8226,
        name: "Potion of Swiftness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8258,
        name: "Potion of Swiftness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16386,
        name: "Splash Potion of Swiftness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16418,
        name: "Splash Potion of Swiftness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16450,
        name: "Splash Potion of Swiftness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8195,
        name: "Potion of Fire Resistance",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8259,
        name: "Potion of Fire Resistance",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16387,
        name: "Splash Potion of Fire Resistance",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16451,
        name: "Splash Potion of Fire Resistance",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8196,
        name: "Potion of Poison",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8228,
        name: "Potion of Poison",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8260,
        name: "Potion of Poison",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16388,
        name: "Splash Potion of Poison",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16420,
        name: "Splash Potion of Poison",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16452,
        name: "Splash Potion of Poison",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8197,
        name: "Potion of Healing",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8229,
        name: "Potion of Healing",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16389,
        name: "Splash Potion of Healing",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16421,
        name: "Splash Potion of Healing",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8198,
        name: "Potion of Night Vision",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8262,
        name: "Potion of Night Vision",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16390,
        name: "Splash Potion of Night Vision",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16454,
        name: "Splash Potion of Night Vision",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8200,
        name: "Potion of Weakness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8264,
        name: "Potion of Weakness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16392,
        name: "Splash Potion of Weakness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16456,
        name: "Splash Potion of Weakness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8201,
        name: "Potion of Strength",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8233,
        name: "Potion of Strength",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8265,
        name: "Potion of Strength",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16393,
        name: "Splash Potion of Strength",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16425,
        name: "Splash Potion of Strength",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16457,
        name: "Splash Potion of Strength",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8202,
        name: "Potion of Slowness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8266,
        name: "Potion of Slowness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16394,
        name: "Splash Potion of Slowness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16458,
        name: "Splash Potion of Slowness",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8203,
        name: "Potion of Leaping",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8235,
        name: "Potion of Leaping",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8267,
        name: "Potion of Leaping",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16395,
        name: "Splash Potion of Leaping",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16427,
        name: "Splash Potion of Leaping",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16459,
        name: "Splash Potion of Leaping",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8204,
        name: "Potion of Harming",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8236,
        name: "Potion of Harming",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16396,
        name: "Splash Potion of Harming",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16428,
        name: "Splash Potion of Harming",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8205,
        name: "Potion of Water Breathing",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8269,
        name: "Potion of Water Breathing",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16397,
        name: "Splash Potion of Water Breathing",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16461,
        name: "Splash Potion of Water Breathing",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8206,
        name: "Potion of Invisibility",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 8270,
        name: "Potion of Invisibility",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16398,
        name: "Splash Potion of Invisibility",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 16462,
        name: "Splash Potion of Invisibility",
        tab: CreativeTab::Brewing,
    },
    SubItem {
        damage: 50,
        name: "Spawn Creeper",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 51,
        name: "Spawn Skeleton",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 52,
        name: "Spawn Spider",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 54,
        name: "Spawn Zombie",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 55,
        name: "Spawn Slime",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 56,
        name: "Spawn Ghast",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 57,
        name: "Spawn Zombie Pigman",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 58,
        name: "Spawn Enderman",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 59,
        name: "Spawn Cave Spider",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 60,
        name: "Spawn Silverfish",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 61,
        name: "Spawn Blaze",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 62,
        name: "Spawn Magma Cube",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 65,
        name: "Spawn Bat",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 66,
        name: "Spawn Witch",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 67,
        name: "Spawn Endermite",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 68,
        name: "Spawn Guardian",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 90,
        name: "Spawn Pig",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 91,
        name: "Spawn Sheep",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 92,
        name: "Spawn Cow",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 93,
        name: "Spawn Chicken",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 94,
        name: "Spawn Squid",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 95,
        name: "Spawn Wolf",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 96,
        name: "Spawn Mooshroom",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 98,
        name: "Spawn Ocelot",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 100,
        name: "Spawn Horse",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 101,
        name: "Spawn Rabbit",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 120,
        name: "Spawn Villager",
        tab: CreativeTab::Misc,
    },
    SubItem {
        damage: 0,
        name: "Skeleton Skull",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Wither Skeleton Skull",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Zombie Head",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Head",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Creeper Head",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 15,
        name: "White Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 14,
        name: "Orange Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 13,
        name: "Magenta Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 12,
        name: "Light Blue Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 11,
        name: "Yellow Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 10,
        name: "Lime Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 9,
        name: "Pink Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 8,
        name: "Gray Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 7,
        name: "Light Gray Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 6,
        name: "Cyan Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 5,
        name: "Purple Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 4,
        name: "Blue Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 3,
        name: "Brown Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 2,
        name: "Green Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 1,
        name: "Red Banner",
        tab: CreativeTab::Decorations,
    },
    SubItem {
        damage: 0,
        name: "Black Banner",
        tab: CreativeTab::Decorations,
    },
];

/// The buildingBlocks tab's ordered list, ascending by registration id.
pub(super) static BUILDING_BLOCKS_ITEMS: [TabEntry; 158] = [
    TabEntry { id: 1, damage: 0 },
    TabEntry { id: 1, damage: 1 },
    TabEntry { id: 1, damage: 2 },
    TabEntry { id: 1, damage: 3 },
    TabEntry { id: 1, damage: 4 },
    TabEntry { id: 1, damage: 5 },
    TabEntry { id: 1, damage: 6 },
    TabEntry { id: 2, damage: 0 },
    TabEntry { id: 3, damage: 0 },
    TabEntry { id: 3, damage: 1 },
    TabEntry { id: 3, damage: 2 },
    TabEntry { id: 4, damage: 0 },
    TabEntry { id: 5, damage: 0 },
    TabEntry { id: 5, damage: 1 },
    TabEntry { id: 5, damage: 2 },
    TabEntry { id: 5, damage: 3 },
    TabEntry { id: 5, damage: 4 },
    TabEntry { id: 5, damage: 5 },
    TabEntry { id: 7, damage: 0 },
    TabEntry { id: 12, damage: 0 },
    TabEntry { id: 12, damage: 1 },
    TabEntry { id: 13, damage: 0 },
    TabEntry { id: 14, damage: 0 },
    TabEntry { id: 15, damage: 0 },
    TabEntry { id: 16, damage: 0 },
    TabEntry { id: 17, damage: 0 },
    TabEntry { id: 17, damage: 1 },
    TabEntry { id: 17, damage: 2 },
    TabEntry { id: 17, damage: 3 },
    TabEntry { id: 19, damage: 0 },
    TabEntry { id: 19, damage: 1 },
    TabEntry { id: 20, damage: 0 },
    TabEntry { id: 21, damage: 0 },
    TabEntry { id: 22, damage: 0 },
    TabEntry { id: 24, damage: 0 },
    TabEntry { id: 24, damage: 1 },
    TabEntry { id: 24, damage: 2 },
    TabEntry { id: 35, damage: 0 },
    TabEntry { id: 35, damage: 1 },
    TabEntry { id: 35, damage: 2 },
    TabEntry { id: 35, damage: 3 },
    TabEntry { id: 35, damage: 4 },
    TabEntry { id: 35, damage: 5 },
    TabEntry { id: 35, damage: 6 },
    TabEntry { id: 35, damage: 7 },
    TabEntry { id: 35, damage: 8 },
    TabEntry { id: 35, damage: 9 },
    TabEntry { id: 35, damage: 10 },
    TabEntry { id: 35, damage: 11 },
    TabEntry { id: 35, damage: 12 },
    TabEntry { id: 35, damage: 13 },
    TabEntry { id: 35, damage: 14 },
    TabEntry { id: 35, damage: 15 },
    TabEntry { id: 41, damage: 0 },
    TabEntry { id: 42, damage: 0 },
    TabEntry { id: 44, damage: 0 },
    TabEntry { id: 44, damage: 1 },
    TabEntry { id: 44, damage: 3 },
    TabEntry { id: 44, damage: 4 },
    TabEntry { id: 44, damage: 5 },
    TabEntry { id: 44, damage: 6 },
    TabEntry { id: 44, damage: 7 },
    TabEntry { id: 45, damage: 0 },
    TabEntry { id: 47, damage: 0 },
    TabEntry { id: 48, damage: 0 },
    TabEntry { id: 49, damage: 0 },
    TabEntry { id: 53, damage: 0 },
    TabEntry { id: 56, damage: 0 },
    TabEntry { id: 57, damage: 0 },
    TabEntry { id: 67, damage: 0 },
    TabEntry { id: 73, damage: 0 },
    TabEntry { id: 79, damage: 0 },
    TabEntry { id: 80, damage: 0 },
    TabEntry { id: 82, damage: 0 },
    TabEntry { id: 86, damage: 0 },
    TabEntry { id: 87, damage: 0 },
    TabEntry { id: 88, damage: 0 },
    TabEntry { id: 89, damage: 0 },
    TabEntry { id: 91, damage: 0 },
    TabEntry { id: 95, damage: 0 },
    TabEntry { id: 95, damage: 1 },
    TabEntry { id: 95, damage: 2 },
    TabEntry { id: 95, damage: 3 },
    TabEntry { id: 95, damage: 4 },
    TabEntry { id: 95, damage: 5 },
    TabEntry { id: 95, damage: 6 },
    TabEntry { id: 95, damage: 7 },
    TabEntry { id: 95, damage: 8 },
    TabEntry { id: 95, damage: 9 },
    TabEntry { id: 95, damage: 10 },
    TabEntry { id: 95, damage: 11 },
    TabEntry { id: 95, damage: 12 },
    TabEntry { id: 95, damage: 13 },
    TabEntry { id: 95, damage: 14 },
    TabEntry { id: 95, damage: 15 },
    TabEntry { id: 98, damage: 0 },
    TabEntry { id: 98, damage: 1 },
    TabEntry { id: 98, damage: 2 },
    TabEntry { id: 98, damage: 3 },
    TabEntry { id: 103, damage: 0 },
    TabEntry { id: 108, damage: 0 },
    TabEntry { id: 109, damage: 0 },
    TabEntry { id: 110, damage: 0 },
    TabEntry { id: 112, damage: 0 },
    TabEntry { id: 114, damage: 0 },
    TabEntry { id: 121, damage: 0 },
    TabEntry { id: 126, damage: 0 },
    TabEntry { id: 126, damage: 1 },
    TabEntry { id: 126, damage: 2 },
    TabEntry { id: 126, damage: 3 },
    TabEntry { id: 126, damage: 4 },
    TabEntry { id: 126, damage: 5 },
    TabEntry { id: 128, damage: 0 },
    TabEntry { id: 129, damage: 0 },
    TabEntry { id: 133, damage: 0 },
    TabEntry { id: 134, damage: 0 },
    TabEntry { id: 135, damage: 0 },
    TabEntry { id: 136, damage: 0 },
    TabEntry { id: 139, damage: 0 },
    TabEntry { id: 139, damage: 1 },
    TabEntry { id: 153, damage: 0 },
    TabEntry { id: 155, damage: 0 },
    TabEntry { id: 155, damage: 1 },
    TabEntry { id: 155, damage: 2 },
    TabEntry { id: 156, damage: 0 },
    TabEntry { id: 159, damage: 0 },
    TabEntry { id: 159, damage: 1 },
    TabEntry { id: 159, damage: 2 },
    TabEntry { id: 159, damage: 3 },
    TabEntry { id: 159, damage: 4 },
    TabEntry { id: 159, damage: 5 },
    TabEntry { id: 159, damage: 6 },
    TabEntry { id: 159, damage: 7 },
    TabEntry { id: 159, damage: 8 },
    TabEntry { id: 159, damage: 9 },
    TabEntry {
        id: 159,
        damage: 10,
    },
    TabEntry {
        id: 159,
        damage: 11,
    },
    TabEntry {
        id: 159,
        damage: 12,
    },
    TabEntry {
        id: 159,
        damage: 13,
    },
    TabEntry {
        id: 159,
        damage: 14,
    },
    TabEntry {
        id: 159,
        damage: 15,
    },
    TabEntry { id: 162, damage: 4 },
    TabEntry { id: 162, damage: 5 },
    TabEntry { id: 163, damage: 0 },
    TabEntry { id: 164, damage: 0 },
    TabEntry { id: 168, damage: 0 },
    TabEntry { id: 168, damage: 1 },
    TabEntry { id: 168, damage: 2 },
    TabEntry { id: 169, damage: 0 },
    TabEntry { id: 170, damage: 0 },
    TabEntry { id: 172, damage: 0 },
    TabEntry { id: 173, damage: 0 },
    TabEntry { id: 174, damage: 0 },
    TabEntry { id: 179, damage: 0 },
    TabEntry { id: 179, damage: 1 },
    TabEntry { id: 179, damage: 2 },
    TabEntry { id: 180, damage: 0 },
    TabEntry { id: 182, damage: 0 },
];

/// The decorations tab's ordered list, ascending by registration id.
pub(super) static DECORATIONS_ITEMS: [TabEntry; 126] = [
    TabEntry { id: 6, damage: 0 },
    TabEntry { id: 6, damage: 1 },
    TabEntry { id: 6, damage: 2 },
    TabEntry { id: 6, damage: 3 },
    TabEntry { id: 6, damage: 4 },
    TabEntry { id: 6, damage: 5 },
    TabEntry { id: 18, damage: 0 },
    TabEntry { id: 18, damage: 1 },
    TabEntry { id: 18, damage: 2 },
    TabEntry { id: 18, damage: 3 },
    TabEntry { id: 30, damage: 0 },
    TabEntry { id: 31, damage: 1 },
    TabEntry { id: 31, damage: 2 },
    TabEntry { id: 32, damage: 0 },
    TabEntry { id: 37, damage: 0 },
    TabEntry { id: 38, damage: 0 },
    TabEntry { id: 38, damage: 1 },
    TabEntry { id: 38, damage: 2 },
    TabEntry { id: 38, damage: 3 },
    TabEntry { id: 38, damage: 4 },
    TabEntry { id: 38, damage: 5 },
    TabEntry { id: 38, damage: 6 },
    TabEntry { id: 38, damage: 7 },
    TabEntry { id: 38, damage: 8 },
    TabEntry { id: 39, damage: 0 },
    TabEntry { id: 40, damage: 0 },
    TabEntry { id: 50, damage: 0 },
    TabEntry { id: 54, damage: 0 },
    TabEntry { id: 58, damage: 0 },
    TabEntry { id: 61, damage: 0 },
    TabEntry { id: 65, damage: 0 },
    TabEntry { id: 78, damage: 0 },
    TabEntry { id: 81, damage: 0 },
    TabEntry { id: 84, damage: 0 },
    TabEntry { id: 85, damage: 0 },
    TabEntry { id: 97, damage: 0 },
    TabEntry { id: 97, damage: 1 },
    TabEntry { id: 97, damage: 2 },
    TabEntry { id: 97, damage: 3 },
    TabEntry { id: 97, damage: 4 },
    TabEntry { id: 97, damage: 5 },
    TabEntry { id: 101, damage: 0 },
    TabEntry { id: 102, damage: 0 },
    TabEntry { id: 106, damage: 0 },
    TabEntry { id: 111, damage: 0 },
    TabEntry { id: 113, damage: 0 },
    TabEntry { id: 116, damage: 0 },
    TabEntry { id: 120, damage: 0 },
    TabEntry { id: 130, damage: 0 },
    TabEntry { id: 145, damage: 0 },
    TabEntry { id: 145, damage: 1 },
    TabEntry { id: 145, damage: 2 },
    TabEntry { id: 146, damage: 0 },
    TabEntry { id: 160, damage: 0 },
    TabEntry { id: 160, damage: 1 },
    TabEntry { id: 160, damage: 2 },
    TabEntry { id: 160, damage: 3 },
    TabEntry { id: 160, damage: 4 },
    TabEntry { id: 160, damage: 5 },
    TabEntry { id: 160, damage: 6 },
    TabEntry { id: 160, damage: 7 },
    TabEntry { id: 160, damage: 8 },
    TabEntry { id: 160, damage: 9 },
    TabEntry {
        id: 160,
        damage: 10,
    },
    TabEntry {
        id: 160,
        damage: 11,
    },
    TabEntry {
        id: 160,
        damage: 12,
    },
    TabEntry {
        id: 160,
        damage: 13,
    },
    TabEntry {
        id: 160,
        damage: 14,
    },
    TabEntry {
        id: 160,
        damage: 15,
    },
    TabEntry { id: 161, damage: 4 },
    TabEntry { id: 161, damage: 5 },
    TabEntry { id: 165, damage: 0 },
    TabEntry { id: 171, damage: 0 },
    TabEntry { id: 171, damage: 1 },
    TabEntry { id: 171, damage: 2 },
    TabEntry { id: 171, damage: 3 },
    TabEntry { id: 171, damage: 4 },
    TabEntry { id: 171, damage: 5 },
    TabEntry { id: 171, damage: 6 },
    TabEntry { id: 171, damage: 7 },
    TabEntry { id: 171, damage: 8 },
    TabEntry { id: 171, damage: 9 },
    TabEntry {
        id: 171,
        damage: 10,
    },
    TabEntry {
        id: 171,
        damage: 11,
    },
    TabEntry {
        id: 171,
        damage: 12,
    },
    TabEntry {
        id: 171,
        damage: 13,
    },
    TabEntry {
        id: 171,
        damage: 14,
    },
    TabEntry {
        id: 171,
        damage: 15,
    },
    TabEntry { id: 175, damage: 0 },
    TabEntry { id: 175, damage: 1 },
    TabEntry { id: 175, damage: 2 },
    TabEntry { id: 175, damage: 3 },
    TabEntry { id: 175, damage: 4 },
    TabEntry { id: 175, damage: 5 },
    TabEntry { id: 188, damage: 0 },
    TabEntry { id: 189, damage: 0 },
    TabEntry { id: 190, damage: 0 },
    TabEntry { id: 191, damage: 0 },
    TabEntry { id: 192, damage: 0 },
    TabEntry { id: 321, damage: 0 },
    TabEntry { id: 323, damage: 0 },
    TabEntry { id: 355, damage: 0 },
    TabEntry { id: 389, damage: 0 },
    TabEntry { id: 390, damage: 0 },
    TabEntry { id: 397, damage: 0 },
    TabEntry { id: 397, damage: 1 },
    TabEntry { id: 397, damage: 2 },
    TabEntry { id: 397, damage: 3 },
    TabEntry { id: 397, damage: 4 },
    TabEntry { id: 416, damage: 0 },
    TabEntry {
        id: 425,
        damage: 15,
    },
    TabEntry {
        id: 425,
        damage: 14,
    },
    TabEntry {
        id: 425,
        damage: 13,
    },
    TabEntry {
        id: 425,
        damage: 12,
    },
    TabEntry {
        id: 425,
        damage: 11,
    },
    TabEntry {
        id: 425,
        damage: 10,
    },
    TabEntry { id: 425, damage: 9 },
    TabEntry { id: 425, damage: 8 },
    TabEntry { id: 425, damage: 7 },
    TabEntry { id: 425, damage: 6 },
    TabEntry { id: 425, damage: 5 },
    TabEntry { id: 425, damage: 4 },
    TabEntry { id: 425, damage: 3 },
    TabEntry { id: 425, damage: 2 },
    TabEntry { id: 425, damage: 1 },
    TabEntry { id: 425, damage: 0 },
];

/// The redstone tab's ordered list, ascending by registration id.
pub(super) static REDSTONE_ITEMS: [TabEntry; 37] = [
    TabEntry { id: 23, damage: 0 },
    TabEntry { id: 25, damage: 0 },
    TabEntry { id: 29, damage: 0 },
    TabEntry { id: 33, damage: 0 },
    TabEntry { id: 46, damage: 0 },
    TabEntry { id: 69, damage: 0 },
    TabEntry { id: 70, damage: 0 },
    TabEntry { id: 72, damage: 0 },
    TabEntry { id: 76, damage: 0 },
    TabEntry { id: 77, damage: 0 },
    TabEntry { id: 96, damage: 0 },
    TabEntry { id: 107, damage: 0 },
    TabEntry { id: 123, damage: 0 },
    TabEntry { id: 131, damage: 0 },
    TabEntry { id: 143, damage: 0 },
    TabEntry { id: 147, damage: 0 },
    TabEntry { id: 148, damage: 0 },
    TabEntry { id: 151, damage: 0 },
    TabEntry { id: 152, damage: 0 },
    TabEntry { id: 154, damage: 0 },
    TabEntry { id: 158, damage: 0 },
    TabEntry { id: 167, damage: 0 },
    TabEntry { id: 183, damage: 0 },
    TabEntry { id: 184, damage: 0 },
    TabEntry { id: 185, damage: 0 },
    TabEntry { id: 186, damage: 0 },
    TabEntry { id: 187, damage: 0 },
    TabEntry { id: 324, damage: 0 },
    TabEntry { id: 330, damage: 0 },
    TabEntry { id: 331, damage: 0 },
    TabEntry { id: 356, damage: 0 },
    TabEntry { id: 404, damage: 0 },
    TabEntry { id: 427, damage: 0 },
    TabEntry { id: 428, damage: 0 },
    TabEntry { id: 429, damage: 0 },
    TabEntry { id: 430, damage: 0 },
    TabEntry { id: 431, damage: 0 },
];

/// The transportation tab's ordered list, ascending by registration id.
pub(super) static TRANSPORTATION_ITEMS: [TabEntry; 13] = [
    TabEntry { id: 27, damage: 0 },
    TabEntry { id: 28, damage: 0 },
    TabEntry { id: 66, damage: 0 },
    TabEntry { id: 157, damage: 0 },
    TabEntry { id: 328, damage: 0 },
    TabEntry { id: 329, damage: 0 },
    TabEntry { id: 333, damage: 0 },
    TabEntry { id: 342, damage: 0 },
    TabEntry { id: 343, damage: 0 },
    TabEntry { id: 398, damage: 0 },
    TabEntry { id: 407, damage: 0 },
    TabEntry { id: 408, damage: 0 },
    TabEntry { id: 422, damage: 0 },
];

/// The misc tab's ordered list, ascending by registration id.
pub(super) static MISC_ITEMS: [TabEntry; 59] = [
    TabEntry { id: 138, damage: 0 },
    TabEntry { id: 325, damage: 0 },
    TabEntry { id: 326, damage: 0 },
    TabEntry { id: 327, damage: 0 },
    TabEntry { id: 332, damage: 0 },
    TabEntry { id: 335, damage: 0 },
    TabEntry { id: 339, damage: 0 },
    TabEntry { id: 340, damage: 0 },
    TabEntry { id: 341, damage: 0 },
    TabEntry { id: 352, damage: 0 },
    TabEntry { id: 368, damage: 0 },
    TabEntry { id: 381, damage: 0 },
    TabEntry {
        id: 383,
        damage: 50,
    },
    TabEntry {
        id: 383,
        damage: 51,
    },
    TabEntry {
        id: 383,
        damage: 52,
    },
    TabEntry {
        id: 383,
        damage: 54,
    },
    TabEntry {
        id: 383,
        damage: 55,
    },
    TabEntry {
        id: 383,
        damage: 56,
    },
    TabEntry {
        id: 383,
        damage: 57,
    },
    TabEntry {
        id: 383,
        damage: 58,
    },
    TabEntry {
        id: 383,
        damage: 59,
    },
    TabEntry {
        id: 383,
        damage: 60,
    },
    TabEntry {
        id: 383,
        damage: 61,
    },
    TabEntry {
        id: 383,
        damage: 62,
    },
    TabEntry {
        id: 383,
        damage: 65,
    },
    TabEntry {
        id: 383,
        damage: 66,
    },
    TabEntry {
        id: 383,
        damage: 67,
    },
    TabEntry {
        id: 383,
        damage: 68,
    },
    TabEntry {
        id: 383,
        damage: 90,
    },
    TabEntry {
        id: 383,
        damage: 91,
    },
    TabEntry {
        id: 383,
        damage: 92,
    },
    TabEntry {
        id: 383,
        damage: 93,
    },
    TabEntry {
        id: 383,
        damage: 94,
    },
    TabEntry {
        id: 383,
        damage: 95,
    },
    TabEntry {
        id: 383,
        damage: 96,
    },
    TabEntry {
        id: 383,
        damage: 98,
    },
    TabEntry {
        id: 383,
        damage: 100,
    },
    TabEntry {
        id: 383,
        damage: 101,
    },
    TabEntry {
        id: 383,
        damage: 120,
    },
    TabEntry { id: 384, damage: 0 },
    TabEntry { id: 385, damage: 0 },
    TabEntry { id: 386, damage: 0 },
    TabEntry { id: 395, damage: 0 },
    TabEntry { id: 402, damage: 0 },
    TabEntry { id: 417, damage: 0 },
    TabEntry { id: 418, damage: 0 },
    TabEntry { id: 419, damage: 0 },
    TabEntry {
        id: 2256,
        damage: 0,
    },
    TabEntry {
        id: 2257,
        damage: 0,
    },
    TabEntry {
        id: 2258,
        damage: 0,
    },
    TabEntry {
        id: 2259,
        damage: 0,
    },
    TabEntry {
        id: 2260,
        damage: 0,
    },
    TabEntry {
        id: 2261,
        damage: 0,
    },
    TabEntry {
        id: 2262,
        damage: 0,
    },
    TabEntry {
        id: 2263,
        damage: 0,
    },
    TabEntry {
        id: 2264,
        damage: 0,
    },
    TabEntry {
        id: 2265,
        damage: 0,
    },
    TabEntry {
        id: 2266,
        damage: 0,
    },
    TabEntry {
        id: 2267,
        damage: 0,
    },
];

/// The search tab's ordered list, ascending by registration id.
pub(super) static SEARCH_ITEMS: [TabEntry; 600] = [
    TabEntry { id: 1, damage: 0 },
    TabEntry { id: 1, damage: 1 },
    TabEntry { id: 1, damage: 2 },
    TabEntry { id: 1, damage: 3 },
    TabEntry { id: 1, damage: 4 },
    TabEntry { id: 1, damage: 5 },
    TabEntry { id: 1, damage: 6 },
    TabEntry { id: 2, damage: 0 },
    TabEntry { id: 3, damage: 0 },
    TabEntry { id: 3, damage: 1 },
    TabEntry { id: 3, damage: 2 },
    TabEntry { id: 4, damage: 0 },
    TabEntry { id: 5, damage: 0 },
    TabEntry { id: 5, damage: 1 },
    TabEntry { id: 5, damage: 2 },
    TabEntry { id: 5, damage: 3 },
    TabEntry { id: 5, damage: 4 },
    TabEntry { id: 5, damage: 5 },
    TabEntry { id: 6, damage: 0 },
    TabEntry { id: 6, damage: 1 },
    TabEntry { id: 6, damage: 2 },
    TabEntry { id: 6, damage: 3 },
    TabEntry { id: 6, damage: 4 },
    TabEntry { id: 6, damage: 5 },
    TabEntry { id: 7, damage: 0 },
    TabEntry { id: 12, damage: 0 },
    TabEntry { id: 12, damage: 1 },
    TabEntry { id: 13, damage: 0 },
    TabEntry { id: 14, damage: 0 },
    TabEntry { id: 15, damage: 0 },
    TabEntry { id: 16, damage: 0 },
    TabEntry { id: 17, damage: 0 },
    TabEntry { id: 17, damage: 1 },
    TabEntry { id: 17, damage: 2 },
    TabEntry { id: 17, damage: 3 },
    TabEntry { id: 18, damage: 0 },
    TabEntry { id: 18, damage: 1 },
    TabEntry { id: 18, damage: 2 },
    TabEntry { id: 18, damage: 3 },
    TabEntry { id: 19, damage: 0 },
    TabEntry { id: 19, damage: 1 },
    TabEntry { id: 20, damage: 0 },
    TabEntry { id: 21, damage: 0 },
    TabEntry { id: 22, damage: 0 },
    TabEntry { id: 23, damage: 0 },
    TabEntry { id: 24, damage: 0 },
    TabEntry { id: 24, damage: 1 },
    TabEntry { id: 24, damage: 2 },
    TabEntry { id: 25, damage: 0 },
    TabEntry { id: 27, damage: 0 },
    TabEntry { id: 28, damage: 0 },
    TabEntry { id: 29, damage: 0 },
    TabEntry { id: 30, damage: 0 },
    TabEntry { id: 31, damage: 1 },
    TabEntry { id: 31, damage: 2 },
    TabEntry { id: 32, damage: 0 },
    TabEntry { id: 33, damage: 0 },
    TabEntry { id: 35, damage: 0 },
    TabEntry { id: 35, damage: 1 },
    TabEntry { id: 35, damage: 2 },
    TabEntry { id: 35, damage: 3 },
    TabEntry { id: 35, damage: 4 },
    TabEntry { id: 35, damage: 5 },
    TabEntry { id: 35, damage: 6 },
    TabEntry { id: 35, damage: 7 },
    TabEntry { id: 35, damage: 8 },
    TabEntry { id: 35, damage: 9 },
    TabEntry { id: 35, damage: 10 },
    TabEntry { id: 35, damage: 11 },
    TabEntry { id: 35, damage: 12 },
    TabEntry { id: 35, damage: 13 },
    TabEntry { id: 35, damage: 14 },
    TabEntry { id: 35, damage: 15 },
    TabEntry { id: 37, damage: 0 },
    TabEntry { id: 38, damage: 0 },
    TabEntry { id: 38, damage: 1 },
    TabEntry { id: 38, damage: 2 },
    TabEntry { id: 38, damage: 3 },
    TabEntry { id: 38, damage: 4 },
    TabEntry { id: 38, damage: 5 },
    TabEntry { id: 38, damage: 6 },
    TabEntry { id: 38, damage: 7 },
    TabEntry { id: 38, damage: 8 },
    TabEntry { id: 39, damage: 0 },
    TabEntry { id: 40, damage: 0 },
    TabEntry { id: 41, damage: 0 },
    TabEntry { id: 42, damage: 0 },
    TabEntry { id: 44, damage: 0 },
    TabEntry { id: 44, damage: 1 },
    TabEntry { id: 44, damage: 3 },
    TabEntry { id: 44, damage: 4 },
    TabEntry { id: 44, damage: 5 },
    TabEntry { id: 44, damage: 6 },
    TabEntry { id: 44, damage: 7 },
    TabEntry { id: 45, damage: 0 },
    TabEntry { id: 46, damage: 0 },
    TabEntry { id: 47, damage: 0 },
    TabEntry { id: 48, damage: 0 },
    TabEntry { id: 49, damage: 0 },
    TabEntry { id: 50, damage: 0 },
    TabEntry { id: 53, damage: 0 },
    TabEntry { id: 54, damage: 0 },
    TabEntry { id: 56, damage: 0 },
    TabEntry { id: 57, damage: 0 },
    TabEntry { id: 58, damage: 0 },
    TabEntry { id: 61, damage: 0 },
    TabEntry { id: 65, damage: 0 },
    TabEntry { id: 66, damage: 0 },
    TabEntry { id: 67, damage: 0 },
    TabEntry { id: 69, damage: 0 },
    TabEntry { id: 70, damage: 0 },
    TabEntry { id: 72, damage: 0 },
    TabEntry { id: 73, damage: 0 },
    TabEntry { id: 76, damage: 0 },
    TabEntry { id: 77, damage: 0 },
    TabEntry { id: 78, damage: 0 },
    TabEntry { id: 79, damage: 0 },
    TabEntry { id: 80, damage: 0 },
    TabEntry { id: 81, damage: 0 },
    TabEntry { id: 82, damage: 0 },
    TabEntry { id: 84, damage: 0 },
    TabEntry { id: 85, damage: 0 },
    TabEntry { id: 86, damage: 0 },
    TabEntry { id: 87, damage: 0 },
    TabEntry { id: 88, damage: 0 },
    TabEntry { id: 89, damage: 0 },
    TabEntry { id: 91, damage: 0 },
    TabEntry { id: 95, damage: 0 },
    TabEntry { id: 95, damage: 1 },
    TabEntry { id: 95, damage: 2 },
    TabEntry { id: 95, damage: 3 },
    TabEntry { id: 95, damage: 4 },
    TabEntry { id: 95, damage: 5 },
    TabEntry { id: 95, damage: 6 },
    TabEntry { id: 95, damage: 7 },
    TabEntry { id: 95, damage: 8 },
    TabEntry { id: 95, damage: 9 },
    TabEntry { id: 95, damage: 10 },
    TabEntry { id: 95, damage: 11 },
    TabEntry { id: 95, damage: 12 },
    TabEntry { id: 95, damage: 13 },
    TabEntry { id: 95, damage: 14 },
    TabEntry { id: 95, damage: 15 },
    TabEntry { id: 96, damage: 0 },
    TabEntry { id: 97, damage: 0 },
    TabEntry { id: 97, damage: 1 },
    TabEntry { id: 97, damage: 2 },
    TabEntry { id: 97, damage: 3 },
    TabEntry { id: 97, damage: 4 },
    TabEntry { id: 97, damage: 5 },
    TabEntry { id: 98, damage: 0 },
    TabEntry { id: 98, damage: 1 },
    TabEntry { id: 98, damage: 2 },
    TabEntry { id: 98, damage: 3 },
    TabEntry { id: 101, damage: 0 },
    TabEntry { id: 102, damage: 0 },
    TabEntry { id: 103, damage: 0 },
    TabEntry { id: 106, damage: 0 },
    TabEntry { id: 107, damage: 0 },
    TabEntry { id: 108, damage: 0 },
    TabEntry { id: 109, damage: 0 },
    TabEntry { id: 110, damage: 0 },
    TabEntry { id: 111, damage: 0 },
    TabEntry { id: 112, damage: 0 },
    TabEntry { id: 113, damage: 0 },
    TabEntry { id: 114, damage: 0 },
    TabEntry { id: 116, damage: 0 },
    TabEntry { id: 120, damage: 0 },
    TabEntry { id: 121, damage: 0 },
    TabEntry { id: 123, damage: 0 },
    TabEntry { id: 126, damage: 0 },
    TabEntry { id: 126, damage: 1 },
    TabEntry { id: 126, damage: 2 },
    TabEntry { id: 126, damage: 3 },
    TabEntry { id: 126, damage: 4 },
    TabEntry { id: 126, damage: 5 },
    TabEntry { id: 128, damage: 0 },
    TabEntry { id: 129, damage: 0 },
    TabEntry { id: 130, damage: 0 },
    TabEntry { id: 131, damage: 0 },
    TabEntry { id: 133, damage: 0 },
    TabEntry { id: 134, damage: 0 },
    TabEntry { id: 135, damage: 0 },
    TabEntry { id: 136, damage: 0 },
    TabEntry { id: 138, damage: 0 },
    TabEntry { id: 139, damage: 0 },
    TabEntry { id: 139, damage: 1 },
    TabEntry { id: 143, damage: 0 },
    TabEntry { id: 145, damage: 0 },
    TabEntry { id: 145, damage: 1 },
    TabEntry { id: 145, damage: 2 },
    TabEntry { id: 146, damage: 0 },
    TabEntry { id: 147, damage: 0 },
    TabEntry { id: 148, damage: 0 },
    TabEntry { id: 151, damage: 0 },
    TabEntry { id: 152, damage: 0 },
    TabEntry { id: 153, damage: 0 },
    TabEntry { id: 154, damage: 0 },
    TabEntry { id: 155, damage: 0 },
    TabEntry { id: 155, damage: 1 },
    TabEntry { id: 155, damage: 2 },
    TabEntry { id: 156, damage: 0 },
    TabEntry { id: 157, damage: 0 },
    TabEntry { id: 158, damage: 0 },
    TabEntry { id: 159, damage: 0 },
    TabEntry { id: 159, damage: 1 },
    TabEntry { id: 159, damage: 2 },
    TabEntry { id: 159, damage: 3 },
    TabEntry { id: 159, damage: 4 },
    TabEntry { id: 159, damage: 5 },
    TabEntry { id: 159, damage: 6 },
    TabEntry { id: 159, damage: 7 },
    TabEntry { id: 159, damage: 8 },
    TabEntry { id: 159, damage: 9 },
    TabEntry {
        id: 159,
        damage: 10,
    },
    TabEntry {
        id: 159,
        damage: 11,
    },
    TabEntry {
        id: 159,
        damage: 12,
    },
    TabEntry {
        id: 159,
        damage: 13,
    },
    TabEntry {
        id: 159,
        damage: 14,
    },
    TabEntry {
        id: 159,
        damage: 15,
    },
    TabEntry { id: 160, damage: 0 },
    TabEntry { id: 160, damage: 1 },
    TabEntry { id: 160, damage: 2 },
    TabEntry { id: 160, damage: 3 },
    TabEntry { id: 160, damage: 4 },
    TabEntry { id: 160, damage: 5 },
    TabEntry { id: 160, damage: 6 },
    TabEntry { id: 160, damage: 7 },
    TabEntry { id: 160, damage: 8 },
    TabEntry { id: 160, damage: 9 },
    TabEntry {
        id: 160,
        damage: 10,
    },
    TabEntry {
        id: 160,
        damage: 11,
    },
    TabEntry {
        id: 160,
        damage: 12,
    },
    TabEntry {
        id: 160,
        damage: 13,
    },
    TabEntry {
        id: 160,
        damage: 14,
    },
    TabEntry {
        id: 160,
        damage: 15,
    },
    TabEntry { id: 161, damage: 4 },
    TabEntry { id: 161, damage: 5 },
    TabEntry { id: 162, damage: 4 },
    TabEntry { id: 162, damage: 5 },
    TabEntry { id: 163, damage: 0 },
    TabEntry { id: 164, damage: 0 },
    TabEntry { id: 165, damage: 0 },
    TabEntry { id: 167, damage: 0 },
    TabEntry { id: 168, damage: 0 },
    TabEntry { id: 168, damage: 1 },
    TabEntry { id: 168, damage: 2 },
    TabEntry { id: 169, damage: 0 },
    TabEntry { id: 170, damage: 0 },
    TabEntry { id: 171, damage: 0 },
    TabEntry { id: 171, damage: 1 },
    TabEntry { id: 171, damage: 2 },
    TabEntry { id: 171, damage: 3 },
    TabEntry { id: 171, damage: 4 },
    TabEntry { id: 171, damage: 5 },
    TabEntry { id: 171, damage: 6 },
    TabEntry { id: 171, damage: 7 },
    TabEntry { id: 171, damage: 8 },
    TabEntry { id: 171, damage: 9 },
    TabEntry {
        id: 171,
        damage: 10,
    },
    TabEntry {
        id: 171,
        damage: 11,
    },
    TabEntry {
        id: 171,
        damage: 12,
    },
    TabEntry {
        id: 171,
        damage: 13,
    },
    TabEntry {
        id: 171,
        damage: 14,
    },
    TabEntry {
        id: 171,
        damage: 15,
    },
    TabEntry { id: 172, damage: 0 },
    TabEntry { id: 173, damage: 0 },
    TabEntry { id: 174, damage: 0 },
    TabEntry { id: 175, damage: 0 },
    TabEntry { id: 175, damage: 1 },
    TabEntry { id: 175, damage: 2 },
    TabEntry { id: 175, damage: 3 },
    TabEntry { id: 175, damage: 4 },
    TabEntry { id: 175, damage: 5 },
    TabEntry { id: 179, damage: 0 },
    TabEntry { id: 179, damage: 1 },
    TabEntry { id: 179, damage: 2 },
    TabEntry { id: 180, damage: 0 },
    TabEntry { id: 182, damage: 0 },
    TabEntry { id: 183, damage: 0 },
    TabEntry { id: 184, damage: 0 },
    TabEntry { id: 185, damage: 0 },
    TabEntry { id: 186, damage: 0 },
    TabEntry { id: 187, damage: 0 },
    TabEntry { id: 188, damage: 0 },
    TabEntry { id: 189, damage: 0 },
    TabEntry { id: 190, damage: 0 },
    TabEntry { id: 191, damage: 0 },
    TabEntry { id: 192, damage: 0 },
    TabEntry { id: 256, damage: 0 },
    TabEntry { id: 257, damage: 0 },
    TabEntry { id: 258, damage: 0 },
    TabEntry { id: 259, damage: 0 },
    TabEntry { id: 260, damage: 0 },
    TabEntry { id: 261, damage: 0 },
    TabEntry { id: 262, damage: 0 },
    TabEntry { id: 263, damage: 0 },
    TabEntry { id: 263, damage: 1 },
    TabEntry { id: 264, damage: 0 },
    TabEntry { id: 265, damage: 0 },
    TabEntry { id: 266, damage: 0 },
    TabEntry { id: 267, damage: 0 },
    TabEntry { id: 268, damage: 0 },
    TabEntry { id: 269, damage: 0 },
    TabEntry { id: 270, damage: 0 },
    TabEntry { id: 271, damage: 0 },
    TabEntry { id: 272, damage: 0 },
    TabEntry { id: 273, damage: 0 },
    TabEntry { id: 274, damage: 0 },
    TabEntry { id: 275, damage: 0 },
    TabEntry { id: 276, damage: 0 },
    TabEntry { id: 277, damage: 0 },
    TabEntry { id: 278, damage: 0 },
    TabEntry { id: 279, damage: 0 },
    TabEntry { id: 280, damage: 0 },
    TabEntry { id: 281, damage: 0 },
    TabEntry { id: 282, damage: 0 },
    TabEntry { id: 283, damage: 0 },
    TabEntry { id: 284, damage: 0 },
    TabEntry { id: 285, damage: 0 },
    TabEntry { id: 286, damage: 0 },
    TabEntry { id: 287, damage: 0 },
    TabEntry { id: 288, damage: 0 },
    TabEntry { id: 289, damage: 0 },
    TabEntry { id: 290, damage: 0 },
    TabEntry { id: 291, damage: 0 },
    TabEntry { id: 292, damage: 0 },
    TabEntry { id: 293, damage: 0 },
    TabEntry { id: 294, damage: 0 },
    TabEntry { id: 295, damage: 0 },
    TabEntry { id: 296, damage: 0 },
    TabEntry { id: 297, damage: 0 },
    TabEntry { id: 298, damage: 0 },
    TabEntry { id: 299, damage: 0 },
    TabEntry { id: 300, damage: 0 },
    TabEntry { id: 301, damage: 0 },
    TabEntry { id: 302, damage: 0 },
    TabEntry { id: 303, damage: 0 },
    TabEntry { id: 304, damage: 0 },
    TabEntry { id: 305, damage: 0 },
    TabEntry { id: 306, damage: 0 },
    TabEntry { id: 307, damage: 0 },
    TabEntry { id: 308, damage: 0 },
    TabEntry { id: 309, damage: 0 },
    TabEntry { id: 310, damage: 0 },
    TabEntry { id: 311, damage: 0 },
    TabEntry { id: 312, damage: 0 },
    TabEntry { id: 313, damage: 0 },
    TabEntry { id: 314, damage: 0 },
    TabEntry { id: 315, damage: 0 },
    TabEntry { id: 316, damage: 0 },
    TabEntry { id: 317, damage: 0 },
    TabEntry { id: 318, damage: 0 },
    TabEntry { id: 319, damage: 0 },
    TabEntry { id: 320, damage: 0 },
    TabEntry { id: 321, damage: 0 },
    TabEntry { id: 322, damage: 0 },
    TabEntry { id: 322, damage: 1 },
    TabEntry { id: 323, damage: 0 },
    TabEntry { id: 324, damage: 0 },
    TabEntry { id: 325, damage: 0 },
    TabEntry { id: 326, damage: 0 },
    TabEntry { id: 327, damage: 0 },
    TabEntry { id: 328, damage: 0 },
    TabEntry { id: 329, damage: 0 },
    TabEntry { id: 330, damage: 0 },
    TabEntry { id: 331, damage: 0 },
    TabEntry { id: 332, damage: 0 },
    TabEntry { id: 333, damage: 0 },
    TabEntry { id: 334, damage: 0 },
    TabEntry { id: 335, damage: 0 },
    TabEntry { id: 336, damage: 0 },
    TabEntry { id: 337, damage: 0 },
    TabEntry { id: 338, damage: 0 },
    TabEntry { id: 339, damage: 0 },
    TabEntry { id: 340, damage: 0 },
    TabEntry { id: 341, damage: 0 },
    TabEntry { id: 342, damage: 0 },
    TabEntry { id: 343, damage: 0 },
    TabEntry { id: 344, damage: 0 },
    TabEntry { id: 345, damage: 0 },
    TabEntry { id: 346, damage: 0 },
    TabEntry { id: 347, damage: 0 },
    TabEntry { id: 348, damage: 0 },
    TabEntry { id: 349, damage: 0 },
    TabEntry { id: 349, damage: 1 },
    TabEntry { id: 349, damage: 2 },
    TabEntry { id: 349, damage: 3 },
    TabEntry { id: 350, damage: 0 },
    TabEntry { id: 350, damage: 1 },
    TabEntry { id: 351, damage: 0 },
    TabEntry { id: 351, damage: 1 },
    TabEntry { id: 351, damage: 2 },
    TabEntry { id: 351, damage: 3 },
    TabEntry { id: 351, damage: 4 },
    TabEntry { id: 351, damage: 5 },
    TabEntry { id: 351, damage: 6 },
    TabEntry { id: 351, damage: 7 },
    TabEntry { id: 351, damage: 8 },
    TabEntry { id: 351, damage: 9 },
    TabEntry {
        id: 351,
        damage: 10,
    },
    TabEntry {
        id: 351,
        damage: 11,
    },
    TabEntry {
        id: 351,
        damage: 12,
    },
    TabEntry {
        id: 351,
        damage: 13,
    },
    TabEntry {
        id: 351,
        damage: 14,
    },
    TabEntry {
        id: 351,
        damage: 15,
    },
    TabEntry { id: 352, damage: 0 },
    TabEntry { id: 353, damage: 0 },
    TabEntry { id: 354, damage: 0 },
    TabEntry { id: 355, damage: 0 },
    TabEntry { id: 356, damage: 0 },
    TabEntry { id: 357, damage: 0 },
    TabEntry { id: 359, damage: 0 },
    TabEntry { id: 360, damage: 0 },
    TabEntry { id: 361, damage: 0 },
    TabEntry { id: 362, damage: 0 },
    TabEntry { id: 363, damage: 0 },
    TabEntry { id: 364, damage: 0 },
    TabEntry { id: 365, damage: 0 },
    TabEntry { id: 366, damage: 0 },
    TabEntry { id: 367, damage: 0 },
    TabEntry { id: 368, damage: 0 },
    TabEntry { id: 369, damage: 0 },
    TabEntry { id: 370, damage: 0 },
    TabEntry { id: 371, damage: 0 },
    TabEntry { id: 372, damage: 0 },
    TabEntry { id: 373, damage: 0 },
    TabEntry {
        id: 373,
        damage: 8193,
    },
    TabEntry {
        id: 373,
        damage: 8225,
    },
    TabEntry {
        id: 373,
        damage: 8257,
    },
    TabEntry {
        id: 373,
        damage: 16385,
    },
    TabEntry {
        id: 373,
        damage: 16417,
    },
    TabEntry {
        id: 373,
        damage: 16449,
    },
    TabEntry {
        id: 373,
        damage: 8194,
    },
    TabEntry {
        id: 373,
        damage: 8226,
    },
    TabEntry {
        id: 373,
        damage: 8258,
    },
    TabEntry {
        id: 373,
        damage: 16386,
    },
    TabEntry {
        id: 373,
        damage: 16418,
    },
    TabEntry {
        id: 373,
        damage: 16450,
    },
    TabEntry {
        id: 373,
        damage: 8195,
    },
    TabEntry {
        id: 373,
        damage: 8259,
    },
    TabEntry {
        id: 373,
        damage: 16387,
    },
    TabEntry {
        id: 373,
        damage: 16451,
    },
    TabEntry {
        id: 373,
        damage: 8196,
    },
    TabEntry {
        id: 373,
        damage: 8228,
    },
    TabEntry {
        id: 373,
        damage: 8260,
    },
    TabEntry {
        id: 373,
        damage: 16388,
    },
    TabEntry {
        id: 373,
        damage: 16420,
    },
    TabEntry {
        id: 373,
        damage: 16452,
    },
    TabEntry {
        id: 373,
        damage: 8197,
    },
    TabEntry {
        id: 373,
        damage: 8229,
    },
    TabEntry {
        id: 373,
        damage: 16389,
    },
    TabEntry {
        id: 373,
        damage: 16421,
    },
    TabEntry {
        id: 373,
        damage: 8198,
    },
    TabEntry {
        id: 373,
        damage: 8262,
    },
    TabEntry {
        id: 373,
        damage: 16390,
    },
    TabEntry {
        id: 373,
        damage: 16454,
    },
    TabEntry {
        id: 373,
        damage: 8200,
    },
    TabEntry {
        id: 373,
        damage: 8264,
    },
    TabEntry {
        id: 373,
        damage: 16392,
    },
    TabEntry {
        id: 373,
        damage: 16456,
    },
    TabEntry {
        id: 373,
        damage: 8201,
    },
    TabEntry {
        id: 373,
        damage: 8233,
    },
    TabEntry {
        id: 373,
        damage: 8265,
    },
    TabEntry {
        id: 373,
        damage: 16393,
    },
    TabEntry {
        id: 373,
        damage: 16425,
    },
    TabEntry {
        id: 373,
        damage: 16457,
    },
    TabEntry {
        id: 373,
        damage: 8202,
    },
    TabEntry {
        id: 373,
        damage: 8266,
    },
    TabEntry {
        id: 373,
        damage: 16394,
    },
    TabEntry {
        id: 373,
        damage: 16458,
    },
    TabEntry {
        id: 373,
        damage: 8203,
    },
    TabEntry {
        id: 373,
        damage: 8235,
    },
    TabEntry {
        id: 373,
        damage: 8267,
    },
    TabEntry {
        id: 373,
        damage: 16395,
    },
    TabEntry {
        id: 373,
        damage: 16427,
    },
    TabEntry {
        id: 373,
        damage: 16459,
    },
    TabEntry {
        id: 373,
        damage: 8204,
    },
    TabEntry {
        id: 373,
        damage: 8236,
    },
    TabEntry {
        id: 373,
        damage: 16396,
    },
    TabEntry {
        id: 373,
        damage: 16428,
    },
    TabEntry {
        id: 373,
        damage: 8205,
    },
    TabEntry {
        id: 373,
        damage: 8269,
    },
    TabEntry {
        id: 373,
        damage: 16397,
    },
    TabEntry {
        id: 373,
        damage: 16461,
    },
    TabEntry {
        id: 373,
        damage: 8206,
    },
    TabEntry {
        id: 373,
        damage: 8270,
    },
    TabEntry {
        id: 373,
        damage: 16398,
    },
    TabEntry {
        id: 373,
        damage: 16462,
    },
    TabEntry { id: 374, damage: 0 },
    TabEntry { id: 375, damage: 0 },
    TabEntry { id: 376, damage: 0 },
    TabEntry { id: 377, damage: 0 },
    TabEntry { id: 378, damage: 0 },
    TabEntry { id: 379, damage: 0 },
    TabEntry { id: 380, damage: 0 },
    TabEntry { id: 381, damage: 0 },
    TabEntry { id: 382, damage: 0 },
    TabEntry {
        id: 383,
        damage: 50,
    },
    TabEntry {
        id: 383,
        damage: 51,
    },
    TabEntry {
        id: 383,
        damage: 52,
    },
    TabEntry {
        id: 383,
        damage: 54,
    },
    TabEntry {
        id: 383,
        damage: 55,
    },
    TabEntry {
        id: 383,
        damage: 56,
    },
    TabEntry {
        id: 383,
        damage: 57,
    },
    TabEntry {
        id: 383,
        damage: 58,
    },
    TabEntry {
        id: 383,
        damage: 59,
    },
    TabEntry {
        id: 383,
        damage: 60,
    },
    TabEntry {
        id: 383,
        damage: 61,
    },
    TabEntry {
        id: 383,
        damage: 62,
    },
    TabEntry {
        id: 383,
        damage: 65,
    },
    TabEntry {
        id: 383,
        damage: 66,
    },
    TabEntry {
        id: 383,
        damage: 67,
    },
    TabEntry {
        id: 383,
        damage: 68,
    },
    TabEntry {
        id: 383,
        damage: 90,
    },
    TabEntry {
        id: 383,
        damage: 91,
    },
    TabEntry {
        id: 383,
        damage: 92,
    },
    TabEntry {
        id: 383,
        damage: 93,
    },
    TabEntry {
        id: 383,
        damage: 94,
    },
    TabEntry {
        id: 383,
        damage: 95,
    },
    TabEntry {
        id: 383,
        damage: 96,
    },
    TabEntry {
        id: 383,
        damage: 98,
    },
    TabEntry {
        id: 383,
        damage: 100,
    },
    TabEntry {
        id: 383,
        damage: 101,
    },
    TabEntry {
        id: 383,
        damage: 120,
    },
    TabEntry { id: 384, damage: 0 },
    TabEntry { id: 385, damage: 0 },
    TabEntry { id: 386, damage: 0 },
    TabEntry { id: 388, damage: 0 },
    TabEntry { id: 389, damage: 0 },
    TabEntry { id: 390, damage: 0 },
    TabEntry { id: 391, damage: 0 },
    TabEntry { id: 392, damage: 0 },
    TabEntry { id: 393, damage: 0 },
    TabEntry { id: 394, damage: 0 },
    TabEntry { id: 395, damage: 0 },
    TabEntry { id: 396, damage: 0 },
    TabEntry { id: 397, damage: 0 },
    TabEntry { id: 397, damage: 1 },
    TabEntry { id: 397, damage: 2 },
    TabEntry { id: 397, damage: 3 },
    TabEntry { id: 397, damage: 4 },
    TabEntry { id: 398, damage: 0 },
    TabEntry { id: 399, damage: 0 },
    TabEntry { id: 400, damage: 0 },
    TabEntry { id: 402, damage: 0 },
    TabEntry { id: 404, damage: 0 },
    TabEntry { id: 405, damage: 0 },
    TabEntry { id: 406, damage: 0 },
    TabEntry { id: 407, damage: 0 },
    TabEntry { id: 408, damage: 0 },
    TabEntry { id: 409, damage: 0 },
    TabEntry { id: 410, damage: 0 },
    TabEntry { id: 411, damage: 0 },
    TabEntry { id: 412, damage: 0 },
    TabEntry { id: 413, damage: 0 },
    TabEntry { id: 414, damage: 0 },
    TabEntry { id: 415, damage: 0 },
    TabEntry { id: 416, damage: 0 },
    TabEntry { id: 417, damage: 0 },
    TabEntry { id: 418, damage: 0 },
    TabEntry { id: 419, damage: 0 },
    TabEntry { id: 420, damage: 0 },
    TabEntry { id: 421, damage: 0 },
    TabEntry { id: 422, damage: 0 },
    TabEntry { id: 423, damage: 0 },
    TabEntry { id: 424, damage: 0 },
    TabEntry {
        id: 425,
        damage: 15,
    },
    TabEntry {
        id: 425,
        damage: 14,
    },
    TabEntry {
        id: 425,
        damage: 13,
    },
    TabEntry {
        id: 425,
        damage: 12,
    },
    TabEntry {
        id: 425,
        damage: 11,
    },
    TabEntry {
        id: 425,
        damage: 10,
    },
    TabEntry { id: 425, damage: 9 },
    TabEntry { id: 425, damage: 8 },
    TabEntry { id: 425, damage: 7 },
    TabEntry { id: 425, damage: 6 },
    TabEntry { id: 425, damage: 5 },
    TabEntry { id: 425, damage: 4 },
    TabEntry { id: 425, damage: 3 },
    TabEntry { id: 425, damage: 2 },
    TabEntry { id: 425, damage: 1 },
    TabEntry { id: 425, damage: 0 },
    TabEntry { id: 427, damage: 0 },
    TabEntry { id: 428, damage: 0 },
    TabEntry { id: 429, damage: 0 },
    TabEntry { id: 430, damage: 0 },
    TabEntry { id: 431, damage: 0 },
    TabEntry {
        id: 2256,
        damage: 0,
    },
    TabEntry {
        id: 2257,
        damage: 0,
    },
    TabEntry {
        id: 2258,
        damage: 0,
    },
    TabEntry {
        id: 2259,
        damage: 0,
    },
    TabEntry {
        id: 2260,
        damage: 0,
    },
    TabEntry {
        id: 2261,
        damage: 0,
    },
    TabEntry {
        id: 2262,
        damage: 0,
    },
    TabEntry {
        id: 2263,
        damage: 0,
    },
    TabEntry {
        id: 2264,
        damage: 0,
    },
    TabEntry {
        id: 2265,
        damage: 0,
    },
    TabEntry {
        id: 2266,
        damage: 0,
    },
    TabEntry {
        id: 2267,
        damage: 0,
    },
];

/// The food tab's ordered list, ascending by registration id.
pub(super) static FOOD_ITEMS: [TabEntry; 32] = [
    TabEntry { id: 260, damage: 0 },
    TabEntry { id: 282, damage: 0 },
    TabEntry { id: 297, damage: 0 },
    TabEntry { id: 319, damage: 0 },
    TabEntry { id: 320, damage: 0 },
    TabEntry { id: 322, damage: 0 },
    TabEntry { id: 322, damage: 1 },
    TabEntry { id: 349, damage: 0 },
    TabEntry { id: 349, damage: 1 },
    TabEntry { id: 349, damage: 2 },
    TabEntry { id: 349, damage: 3 },
    TabEntry { id: 350, damage: 0 },
    TabEntry { id: 350, damage: 1 },
    TabEntry { id: 354, damage: 0 },
    TabEntry { id: 357, damage: 0 },
    TabEntry { id: 360, damage: 0 },
    TabEntry { id: 363, damage: 0 },
    TabEntry { id: 364, damage: 0 },
    TabEntry { id: 365, damage: 0 },
    TabEntry { id: 366, damage: 0 },
    TabEntry { id: 367, damage: 0 },
    TabEntry { id: 375, damage: 0 },
    TabEntry { id: 391, damage: 0 },
    TabEntry { id: 392, damage: 0 },
    TabEntry { id: 393, damage: 0 },
    TabEntry { id: 394, damage: 0 },
    TabEntry { id: 400, damage: 0 },
    TabEntry { id: 411, damage: 0 },
    TabEntry { id: 412, damage: 0 },
    TabEntry { id: 413, damage: 0 },
    TabEntry { id: 423, damage: 0 },
    TabEntry { id: 424, damage: 0 },
];

/// The tools tab's ordered list, ascending by registration id.
pub(super) static TOOLS_ITEMS: [TabEntry; 27] = [
    TabEntry { id: 256, damage: 0 },
    TabEntry { id: 257, damage: 0 },
    TabEntry { id: 258, damage: 0 },
    TabEntry { id: 259, damage: 0 },
    TabEntry { id: 269, damage: 0 },
    TabEntry { id: 270, damage: 0 },
    TabEntry { id: 271, damage: 0 },
    TabEntry { id: 273, damage: 0 },
    TabEntry { id: 274, damage: 0 },
    TabEntry { id: 275, damage: 0 },
    TabEntry { id: 277, damage: 0 },
    TabEntry { id: 278, damage: 0 },
    TabEntry { id: 279, damage: 0 },
    TabEntry { id: 284, damage: 0 },
    TabEntry { id: 285, damage: 0 },
    TabEntry { id: 286, damage: 0 },
    TabEntry { id: 290, damage: 0 },
    TabEntry { id: 291, damage: 0 },
    TabEntry { id: 292, damage: 0 },
    TabEntry { id: 293, damage: 0 },
    TabEntry { id: 294, damage: 0 },
    TabEntry { id: 345, damage: 0 },
    TabEntry { id: 346, damage: 0 },
    TabEntry { id: 347, damage: 0 },
    TabEntry { id: 359, damage: 0 },
    TabEntry { id: 420, damage: 0 },
    TabEntry { id: 421, damage: 0 },
];

/// The combat tab's ordered list, ascending by registration id.
pub(super) static COMBAT_ITEMS: [TabEntry; 27] = [
    TabEntry { id: 261, damage: 0 },
    TabEntry { id: 262, damage: 0 },
    TabEntry { id: 267, damage: 0 },
    TabEntry { id: 268, damage: 0 },
    TabEntry { id: 272, damage: 0 },
    TabEntry { id: 276, damage: 0 },
    TabEntry { id: 283, damage: 0 },
    TabEntry { id: 298, damage: 0 },
    TabEntry { id: 299, damage: 0 },
    TabEntry { id: 300, damage: 0 },
    TabEntry { id: 301, damage: 0 },
    TabEntry { id: 302, damage: 0 },
    TabEntry { id: 303, damage: 0 },
    TabEntry { id: 304, damage: 0 },
    TabEntry { id: 305, damage: 0 },
    TabEntry { id: 306, damage: 0 },
    TabEntry { id: 307, damage: 0 },
    TabEntry { id: 308, damage: 0 },
    TabEntry { id: 309, damage: 0 },
    TabEntry { id: 310, damage: 0 },
    TabEntry { id: 311, damage: 0 },
    TabEntry { id: 312, damage: 0 },
    TabEntry { id: 313, damage: 0 },
    TabEntry { id: 314, damage: 0 },
    TabEntry { id: 315, damage: 0 },
    TabEntry { id: 316, damage: 0 },
    TabEntry { id: 317, damage: 0 },
];

/// The brewing tab's ordered list, ascending by registration id.
pub(super) static BREWING_ITEMS: [TabEntry; 73] = [
    TabEntry { id: 370, damage: 0 },
    TabEntry { id: 373, damage: 0 },
    TabEntry {
        id: 373,
        damage: 8193,
    },
    TabEntry {
        id: 373,
        damage: 8225,
    },
    TabEntry {
        id: 373,
        damage: 8257,
    },
    TabEntry {
        id: 373,
        damage: 16385,
    },
    TabEntry {
        id: 373,
        damage: 16417,
    },
    TabEntry {
        id: 373,
        damage: 16449,
    },
    TabEntry {
        id: 373,
        damage: 8194,
    },
    TabEntry {
        id: 373,
        damage: 8226,
    },
    TabEntry {
        id: 373,
        damage: 8258,
    },
    TabEntry {
        id: 373,
        damage: 16386,
    },
    TabEntry {
        id: 373,
        damage: 16418,
    },
    TabEntry {
        id: 373,
        damage: 16450,
    },
    TabEntry {
        id: 373,
        damage: 8195,
    },
    TabEntry {
        id: 373,
        damage: 8259,
    },
    TabEntry {
        id: 373,
        damage: 16387,
    },
    TabEntry {
        id: 373,
        damage: 16451,
    },
    TabEntry {
        id: 373,
        damage: 8196,
    },
    TabEntry {
        id: 373,
        damage: 8228,
    },
    TabEntry {
        id: 373,
        damage: 8260,
    },
    TabEntry {
        id: 373,
        damage: 16388,
    },
    TabEntry {
        id: 373,
        damage: 16420,
    },
    TabEntry {
        id: 373,
        damage: 16452,
    },
    TabEntry {
        id: 373,
        damage: 8197,
    },
    TabEntry {
        id: 373,
        damage: 8229,
    },
    TabEntry {
        id: 373,
        damage: 16389,
    },
    TabEntry {
        id: 373,
        damage: 16421,
    },
    TabEntry {
        id: 373,
        damage: 8198,
    },
    TabEntry {
        id: 373,
        damage: 8262,
    },
    TabEntry {
        id: 373,
        damage: 16390,
    },
    TabEntry {
        id: 373,
        damage: 16454,
    },
    TabEntry {
        id: 373,
        damage: 8200,
    },
    TabEntry {
        id: 373,
        damage: 8264,
    },
    TabEntry {
        id: 373,
        damage: 16392,
    },
    TabEntry {
        id: 373,
        damage: 16456,
    },
    TabEntry {
        id: 373,
        damage: 8201,
    },
    TabEntry {
        id: 373,
        damage: 8233,
    },
    TabEntry {
        id: 373,
        damage: 8265,
    },
    TabEntry {
        id: 373,
        damage: 16393,
    },
    TabEntry {
        id: 373,
        damage: 16425,
    },
    TabEntry {
        id: 373,
        damage: 16457,
    },
    TabEntry {
        id: 373,
        damage: 8202,
    },
    TabEntry {
        id: 373,
        damage: 8266,
    },
    TabEntry {
        id: 373,
        damage: 16394,
    },
    TabEntry {
        id: 373,
        damage: 16458,
    },
    TabEntry {
        id: 373,
        damage: 8203,
    },
    TabEntry {
        id: 373,
        damage: 8235,
    },
    TabEntry {
        id: 373,
        damage: 8267,
    },
    TabEntry {
        id: 373,
        damage: 16395,
    },
    TabEntry {
        id: 373,
        damage: 16427,
    },
    TabEntry {
        id: 373,
        damage: 16459,
    },
    TabEntry {
        id: 373,
        damage: 8204,
    },
    TabEntry {
        id: 373,
        damage: 8236,
    },
    TabEntry {
        id: 373,
        damage: 16396,
    },
    TabEntry {
        id: 373,
        damage: 16428,
    },
    TabEntry {
        id: 373,
        damage: 8205,
    },
    TabEntry {
        id: 373,
        damage: 8269,
    },
    TabEntry {
        id: 373,
        damage: 16397,
    },
    TabEntry {
        id: 373,
        damage: 16461,
    },
    TabEntry {
        id: 373,
        damage: 8206,
    },
    TabEntry {
        id: 373,
        damage: 8270,
    },
    TabEntry {
        id: 373,
        damage: 16398,
    },
    TabEntry {
        id: 373,
        damage: 16462,
    },
    TabEntry { id: 374, damage: 0 },
    TabEntry { id: 376, damage: 0 },
    TabEntry { id: 377, damage: 0 },
    TabEntry { id: 378, damage: 0 },
    TabEntry { id: 379, damage: 0 },
    TabEntry { id: 380, damage: 0 },
    TabEntry { id: 382, damage: 0 },
    TabEntry { id: 396, damage: 0 },
    TabEntry { id: 414, damage: 0 },
];

/// The materials tab's ordered list, ascending by registration id.
pub(super) static MATERIALS_ITEMS: [TabEntry; 48] = [
    TabEntry { id: 263, damage: 0 },
    TabEntry { id: 263, damage: 1 },
    TabEntry { id: 264, damage: 0 },
    TabEntry { id: 265, damage: 0 },
    TabEntry { id: 266, damage: 0 },
    TabEntry { id: 280, damage: 0 },
    TabEntry { id: 281, damage: 0 },
    TabEntry { id: 287, damage: 0 },
    TabEntry { id: 288, damage: 0 },
    TabEntry { id: 289, damage: 0 },
    TabEntry { id: 295, damage: 0 },
    TabEntry { id: 296, damage: 0 },
    TabEntry { id: 318, damage: 0 },
    TabEntry { id: 334, damage: 0 },
    TabEntry { id: 336, damage: 0 },
    TabEntry { id: 337, damage: 0 },
    TabEntry { id: 338, damage: 0 },
    TabEntry { id: 344, damage: 0 },
    TabEntry { id: 348, damage: 0 },
    TabEntry { id: 351, damage: 0 },
    TabEntry { id: 351, damage: 1 },
    TabEntry { id: 351, damage: 2 },
    TabEntry { id: 351, damage: 3 },
    TabEntry { id: 351, damage: 4 },
    TabEntry { id: 351, damage: 5 },
    TabEntry { id: 351, damage: 6 },
    TabEntry { id: 351, damage: 7 },
    TabEntry { id: 351, damage: 8 },
    TabEntry { id: 351, damage: 9 },
    TabEntry {
        id: 351,
        damage: 10,
    },
    TabEntry {
        id: 351,
        damage: 11,
    },
    TabEntry {
        id: 351,
        damage: 12,
    },
    TabEntry {
        id: 351,
        damage: 13,
    },
    TabEntry {
        id: 351,
        damage: 14,
    },
    TabEntry {
        id: 351,
        damage: 15,
    },
    TabEntry { id: 353, damage: 0 },
    TabEntry { id: 361, damage: 0 },
    TabEntry { id: 362, damage: 0 },
    TabEntry { id: 369, damage: 0 },
    TabEntry { id: 371, damage: 0 },
    TabEntry { id: 372, damage: 0 },
    TabEntry { id: 388, damage: 0 },
    TabEntry { id: 399, damage: 0 },
    TabEntry { id: 405, damage: 0 },
    TabEntry { id: 406, damage: 0 },
    TabEntry { id: 409, damage: 0 },
    TabEntry { id: 410, damage: 0 },
    TabEntry { id: 415, damage: 0 },
];

/// The inventory tab's ordered list, ascending by registration id.
pub(super) static INVENTORY_ITEMS: [TabEntry; 0] = [];

/// The potion registry (`Potion.potionTypes`), ascending by id.
pub(super) static POTION_NAMES: [PotionName; 23] = [
    PotionName {
        id: 1,
        key: "potion.moveSpeed",
        name: "Speed",
        postfix: "Potion of Swiftness",
    },
    PotionName {
        id: 2,
        key: "potion.moveSlowdown",
        name: "Slowness",
        postfix: "Potion of Slowness",
    },
    PotionName {
        id: 3,
        key: "potion.digSpeed",
        name: "Haste",
        postfix: "Potion of Haste",
    },
    PotionName {
        id: 4,
        key: "potion.digSlowDown",
        name: "Mining Fatigue",
        postfix: "Potion of Dullness",
    },
    PotionName {
        id: 5,
        key: "potion.damageBoost",
        name: "Strength",
        postfix: "Potion of Strength",
    },
    PotionName {
        id: 6,
        key: "potion.heal",
        name: "Instant Health",
        postfix: "Potion of Healing",
    },
    PotionName {
        id: 7,
        key: "potion.harm",
        name: "Instant Damage",
        postfix: "Potion of Harming",
    },
    PotionName {
        id: 8,
        key: "potion.jump",
        name: "Jump Boost",
        postfix: "Potion of Leaping",
    },
    PotionName {
        id: 9,
        key: "potion.confusion",
        name: "Nausea",
        postfix: "Potion of Nausea",
    },
    PotionName {
        id: 10,
        key: "potion.regeneration",
        name: "Regeneration",
        postfix: "Potion of Regeneration",
    },
    PotionName {
        id: 11,
        key: "potion.resistance",
        name: "Resistance",
        postfix: "Potion of Resistance",
    },
    PotionName {
        id: 12,
        key: "potion.fireResistance",
        name: "Fire Resistance",
        postfix: "Potion of Fire Resistance",
    },
    PotionName {
        id: 13,
        key: "potion.waterBreathing",
        name: "Water Breathing",
        postfix: "Potion of Water Breathing",
    },
    PotionName {
        id: 14,
        key: "potion.invisibility",
        name: "Invisibility",
        postfix: "Potion of Invisibility",
    },
    PotionName {
        id: 15,
        key: "potion.blindness",
        name: "Blindness",
        postfix: "Potion of Blindness",
    },
    PotionName {
        id: 16,
        key: "potion.nightVision",
        name: "Night Vision",
        postfix: "Potion of Night Vision",
    },
    PotionName {
        id: 17,
        key: "potion.hunger",
        name: "Hunger",
        postfix: "Potion of Hunger",
    },
    PotionName {
        id: 18,
        key: "potion.weakness",
        name: "Weakness",
        postfix: "Potion of Weakness",
    },
    PotionName {
        id: 19,
        key: "potion.poison",
        name: "Poison",
        postfix: "Potion of Poison",
    },
    PotionName {
        id: 20,
        key: "potion.wither",
        name: "Wither",
        postfix: "Potion of Decay",
    },
    PotionName {
        id: 21,
        key: "potion.healthBoost",
        name: "Health Boost",
        postfix: "Potion of Health Boost",
    },
    PotionName {
        id: 22,
        key: "potion.absorption",
        name: "Absorption",
        postfix: "Potion of Absorption",
    },
    PotionName {
        id: 23,
        key: "potion.saturation",
        name: "Saturation",
        postfix: "Potion of Saturation",
    },
];
