//! The item registry table's data: one [`ItemEntry`] per source registration,
//! ascending by id.
//!
//! Derived from the MCP-919 reference tree (never copied): the registration
//! order and ids from `Item.registerItems` (`item/Item.java`:511-953), the block
//! items' registry ids and unlocalized names from `Block.registerBlocks`
//! (`block/Block.java`), the meta-0 model selection from
//! `RenderItem.registerItems` (`client/renderer/entity/RenderItem.java`:522-1068)
//! and the `ItemMeshDefinition` registrations beside it, and the display strings
//! from the en_US language file (which the repository never carries; only the
//! strings it defines are committed). The per-class derivations are recorded in
//! `refs/m5-task-8/derive.py` and pinned by the tests.

use super::{ItemAttributes, ItemEntry, ItemModel};
use oxide_assets::model::BuiltinItem;

pub(super) static TABLE: [ItemEntry; 337] = [
    ItemEntry {
        id: 1,
        name: "Stone",
        resolution: ItemModel::Block("block/stone"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 2,
        name: "Grass Block",
        resolution: ItemModel::Block("block/grass_normal"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 3,
        name: "Dirt",
        resolution: ItemModel::Block("block/dirt"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 4,
        name: "Cobblestone",
        resolution: ItemModel::Block("block/cobblestone"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 5,
        name: "Oak Wood Planks",
        resolution: ItemModel::Block("block/oak_planks"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 6,
        name: "Oak Sapling",
        resolution: ItemModel::Generated(&["blocks/sapling_oak"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 7,
        name: "Bedrock",
        resolution: ItemModel::Block("block/bedrock"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 12,
        name: "Sand",
        resolution: ItemModel::Block("block/sand"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 13,
        name: "Gravel",
        resolution: ItemModel::Block("block/gravel"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 14,
        name: "Gold Ore",
        resolution: ItemModel::Block("block/gold_ore"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 15,
        name: "Iron Ore",
        resolution: ItemModel::Block("block/iron_ore"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 16,
        name: "Coal Ore",
        resolution: ItemModel::Block("block/coal_ore"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 17,
        name: "Oak Wood",
        resolution: ItemModel::Block("block/oak_log"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 18,
        name: "Oak Leaves",
        resolution: ItemModel::Block("block/oak_leaves"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 19,
        name: "Sponge",
        resolution: ItemModel::Block("block/sponge"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 20,
        name: "Glass",
        resolution: ItemModel::Block("block/glass"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 21,
        name: "Lapis Lazuli Ore",
        resolution: ItemModel::Block("block/lapis_ore"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 22,
        name: "Lapis Lazuli Block",
        resolution: ItemModel::Block("block/lapis_block"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 23,
        name: "Dispenser",
        resolution: ItemModel::Block("block/dispenser"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 24,
        name: "Sandstone",
        resolution: ItemModel::Block("block/sandstone_normal"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 25,
        name: "Note Block",
        resolution: ItemModel::Block("block/noteblock"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 27,
        name: "Powered Rail",
        resolution: ItemModel::Generated(&["blocks/rail_golden"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 28,
        name: "Detector Rail",
        resolution: ItemModel::Generated(&["blocks/rail_detector"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 29,
        name: "Sticky Piston",
        resolution: ItemModel::Block("block/piston_inventory_sticky"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 30,
        name: "Cobweb",
        resolution: ItemModel::Generated(&["blocks/web"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 31,
        name: "Shrub",
        resolution: ItemModel::Generated(&["blocks/deadbush"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 32,
        name: "Dead Bush",
        resolution: ItemModel::Generated(&["blocks/deadbush"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 33,
        name: "Piston",
        resolution: ItemModel::Block("block/piston_inventory_normal"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 35,
        name: "Wool",
        resolution: ItemModel::Block("block/white_wool"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 37,
        name: "Dandelion",
        resolution: ItemModel::Generated(&["blocks/flower_dandelion"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 38,
        name: "Poppy",
        resolution: ItemModel::Generated(&["blocks/flower_rose"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 39,
        name: "Mushroom",
        resolution: ItemModel::Generated(&["blocks/mushroom_brown"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 40,
        name: "Mushroom",
        resolution: ItemModel::Generated(&["blocks/mushroom_red"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 41,
        name: "Block of Gold",
        resolution: ItemModel::Block("block/gold_block"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 42,
        name: "Block of Iron",
        resolution: ItemModel::Block("block/iron_block"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 44,
        name: "Stone Slab",
        resolution: ItemModel::Block("block/half_slab_stone"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 45,
        name: "Bricks",
        resolution: ItemModel::Block("block/brick"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 46,
        name: "TNT",
        resolution: ItemModel::Block("block/tnt"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 47,
        name: "Bookshelf",
        resolution: ItemModel::Block("block/bookshelf"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 48,
        name: "Moss Stone",
        resolution: ItemModel::Block("block/mossy_cobblestone"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 49,
        name: "Obsidian",
        resolution: ItemModel::Block("block/obsidian"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 50,
        name: "Torch",
        resolution: ItemModel::Generated(&["blocks/torch_on"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 52,
        name: "Monster Spawner",
        resolution: ItemModel::Block("block/mob_spawner_cage"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 53,
        name: "Oak Wood Stairs",
        resolution: ItemModel::Block("block/oak_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 54,
        name: "Chest",
        resolution: ItemModel::Builtin(BuiltinItem::Chest),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 56,
        name: "Diamond Ore",
        resolution: ItemModel::Block("block/diamond_ore"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 57,
        name: "Block of Diamond",
        resolution: ItemModel::Block("block/diamond_block"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 58,
        name: "Crafting Table",
        resolution: ItemModel::Block("block/crafting_table"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 60,
        name: "Farmland",
        resolution: ItemModel::Block("block/farmland_dry"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 61,
        name: "Furnace",
        resolution: ItemModel::Block("block/furnace"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 62,
        name: "Furnace",
        resolution: ItemModel::Block("block/lit_furnace"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 65,
        name: "Ladder",
        resolution: ItemModel::Generated(&["blocks/ladder"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 66,
        name: "Rail",
        resolution: ItemModel::Generated(&["blocks/rail_normal"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 67,
        name: "Cobblestone Stairs",
        resolution: ItemModel::Block("block/stone_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 69,
        name: "Lever",
        resolution: ItemModel::Generated(&["blocks/lever"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 70,
        name: "Stone Pressure Plate",
        resolution: ItemModel::Block("block/stone_pressure_plate_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 72,
        name: "Wooden Pressure Plate",
        resolution: ItemModel::Block("block/wooden_pressure_plate_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 73,
        name: "Redstone Ore",
        resolution: ItemModel::Block("block/redstone_ore"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 76,
        name: "Redstone Torch",
        resolution: ItemModel::Generated(&["blocks/redstone_torch_on"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 77,
        name: "Button",
        resolution: ItemModel::Block("block/stone_button_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 78,
        name: "Snow",
        resolution: ItemModel::Block("block/snow_height2"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 79,
        name: "Ice",
        resolution: ItemModel::Block("block/ice"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 80,
        name: "Snow",
        resolution: ItemModel::Block("block/snow"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 81,
        name: "Cactus",
        resolution: ItemModel::Block("block/cactus"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 82,
        name: "Clay",
        resolution: ItemModel::Block("block/clay"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 84,
        name: "Jukebox",
        resolution: ItemModel::Block("block/jukebox"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 85,
        name: "Oak Fence",
        resolution: ItemModel::Block("block/oak_fence_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 86,
        name: "Pumpkin",
        resolution: ItemModel::Block("block/pumpkin"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 87,
        name: "Netherrack",
        resolution: ItemModel::Block("block/netherrack"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 88,
        name: "Soul Sand",
        resolution: ItemModel::Block("block/soul_sand"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 89,
        name: "Glowstone",
        resolution: ItemModel::Block("block/glowstone"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 91,
        name: "Jack o'Lantern",
        resolution: ItemModel::Block("block/lit_pumpkin"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 95,
        name: "White Stained Glass",
        resolution: ItemModel::Block("block/glass_white"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 96,
        name: "Wooden Trapdoor",
        resolution: ItemModel::Block("block/wooden_trapdoor_bottom"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 97,
        name: "Stone Monster Egg",
        resolution: ItemModel::Block("block/stone"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 98,
        name: "Stone Bricks",
        resolution: ItemModel::Block("block/stonebrick_normal"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 99,
        name: "Mushroom",
        resolution: ItemModel::Block("block/brown_mushroom_block_cap_all"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 100,
        name: "Mushroom",
        resolution: ItemModel::Block("block/red_mushroom_block_cap_all"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 101,
        name: "Iron Bars",
        resolution: ItemModel::Generated(&["blocks/iron_bars"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 102,
        name: "Glass Pane",
        resolution: ItemModel::Generated(&["blocks/glass"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 103,
        name: "Melon",
        resolution: ItemModel::Block("block/melon"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 106,
        name: "Vines",
        resolution: ItemModel::Generated(&["blocks/vine"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 107,
        name: "Oak Fence Gate",
        resolution: ItemModel::Block("block/oak_fence_gate_closed"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 108,
        name: "Brick Stairs",
        resolution: ItemModel::Block("block/brick_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 109,
        name: "Stone Brick Stairs",
        resolution: ItemModel::Block("block/stone_brick_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 110,
        name: "Mycelium",
        resolution: ItemModel::Block("block/mycelium"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 111,
        name: "Lily Pad",
        resolution: ItemModel::Generated(&["blocks/waterlily"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 112,
        name: "Nether Brick",
        resolution: ItemModel::Block("block/nether_brick"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 113,
        name: "Nether Brick Fence",
        resolution: ItemModel::Block("block/nether_brick_fence_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 114,
        name: "Nether Brick Stairs",
        resolution: ItemModel::Block("block/nether_brick_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 116,
        name: "Enchantment Table",
        resolution: ItemModel::Block("block/enchanting_table_base"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 120,
        name: "End Portal",
        resolution: ItemModel::Block("block/end_portal_frame_empty"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 121,
        name: "End Stone",
        resolution: ItemModel::Block("block/end_stone"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 122,
        name: "Dragon Egg",
        resolution: ItemModel::Block("block/dragon_egg"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 123,
        name: "Redstone Lamp",
        resolution: ItemModel::Block("block/unlit_redstone_lamp"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 126,
        name: "Oak Wood Slab",
        resolution: ItemModel::Block("block/half_slab_oak"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 128,
        name: "Sandstone Stairs",
        resolution: ItemModel::Block("block/sandstone_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 129,
        name: "Emerald Ore",
        resolution: ItemModel::Block("block/emerald_ore"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 130,
        name: "Ender Chest",
        resolution: ItemModel::Builtin(BuiltinItem::EnderChest),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 131,
        name: "Tripwire Hook",
        resolution: ItemModel::Generated(&["blocks/trip_wire_source"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 133,
        name: "Block of Emerald",
        resolution: ItemModel::Block("block/emerald_block"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 134,
        name: "Spruce Wood Stairs",
        resolution: ItemModel::Block("block/spruce_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 135,
        name: "Birch Wood Stairs",
        resolution: ItemModel::Block("block/birch_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 136,
        name: "Jungle Wood Stairs",
        resolution: ItemModel::Block("block/jungle_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 137,
        name: "Command Block",
        resolution: ItemModel::Block("block/command_block"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 138,
        name: "Beacon",
        resolution: ItemModel::Block("block/beacon"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 139,
        name: "Cobblestone Wall",
        resolution: ItemModel::Block("block/cobblestone_wall_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 143,
        name: "Button",
        resolution: ItemModel::Block("block/wooden_button_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 145,
        name: "Anvil",
        resolution: ItemModel::Block("block/anvil_undamaged"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 146,
        name: "Trapped Chest",
        resolution: ItemModel::Builtin(BuiltinItem::TrappedChest),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 147,
        name: "Weighted Pressure Plate (Light)",
        resolution: ItemModel::Block("block/light_pressure_plate_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 148,
        name: "Weighted Pressure Plate (Heavy)",
        resolution: ItemModel::Block("block/heavy_pressure_plate_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 151,
        name: "Daylight Sensor",
        resolution: ItemModel::Block("block/daylight_detector"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 152,
        name: "Block of Redstone",
        resolution: ItemModel::Block("block/redstone_block"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 153,
        name: "Nether Quartz Ore",
        resolution: ItemModel::Block("block/quartz_ore"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 154,
        name: "Hopper",
        resolution: ItemModel::Generated(&["items/hopper"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 155,
        name: "Block of Quartz",
        resolution: ItemModel::Block("block/quartz_normal"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 156,
        name: "Quartz Stairs",
        resolution: ItemModel::Block("block/quartz_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 157,
        name: "Activator Rail",
        resolution: ItemModel::Generated(&["blocks/rail_activator"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 158,
        name: "Dropper",
        resolution: ItemModel::Block("block/dropper"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 159,
        name: "White Stained Clay",
        resolution: ItemModel::Block("block/hardened_clay_white"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 160,
        name: "White Stained Glass Pane",
        resolution: ItemModel::Generated(&["blocks/glass_white"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 161,
        name: "Acacia Leaves",
        resolution: ItemModel::Block("block/acacia_leaves"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 162,
        name: "Acacia Wood",
        resolution: ItemModel::Block("block/acacia_log"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 163,
        name: "Acacia Wood Stairs",
        resolution: ItemModel::Block("block/acacia_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 164,
        name: "Dark Oak Wood Stairs",
        resolution: ItemModel::Block("block/dark_oak_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 165,
        name: "Slime Block",
        resolution: ItemModel::Block("block/slime"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 166,
        name: "Barrier",
        resolution: ItemModel::Generated(&["items/barrier"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 167,
        name: "Iron Trapdoor",
        resolution: ItemModel::Block("block/iron_trapdoor_bottom"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 168,
        name: "Prismarine",
        resolution: ItemModel::Block("block/prismarine_rough"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 169,
        name: "Sea Lantern",
        resolution: ItemModel::Block("block/sea_lantern"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 170,
        name: "Hay Bale",
        resolution: ItemModel::Block("block/hay"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 171,
        name: "Carpet",
        resolution: ItemModel::Block("block/carpet_white"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 172,
        name: "Hardened Clay",
        resolution: ItemModel::Block("block/hardened_clay"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 173,
        name: "Block of Coal",
        resolution: ItemModel::Block("block/coal_block"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 174,
        name: "Packed Ice",
        resolution: ItemModel::Block("block/packed_ice"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 175,
        name: "Sunflower",
        resolution: ItemModel::Generated(&["blocks/double_plant_sunflower_front"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 179,
        name: "Red Sandstone",
        resolution: ItemModel::Block("block/red_sandstone_normal"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 180,
        name: "Red Sandstone Stairs",
        resolution: ItemModel::Block("block/red_sandstone_stairs"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 182,
        name: "Red Sandstone Slab",
        resolution: ItemModel::Block("block/half_slab_red_sandstone"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 183,
        name: "Spruce Fence Gate",
        resolution: ItemModel::Block("block/spruce_fence_gate_closed"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 184,
        name: "Birch Fence Gate",
        resolution: ItemModel::Block("block/birch_fence_gate_closed"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 185,
        name: "Jungle Fence Gate",
        resolution: ItemModel::Block("block/jungle_fence_gate_closed"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 186,
        name: "Dark Oak Fence Gate",
        resolution: ItemModel::Block("block/dark_oak_fence_gate_closed"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 187,
        name: "Acacia Fence Gate",
        resolution: ItemModel::Block("block/acacia_fence_gate_closed"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 188,
        name: "Spruce Fence",
        resolution: ItemModel::Block("block/spruce_fence_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 189,
        name: "Birch Fence",
        resolution: ItemModel::Block("block/birch_fence_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 190,
        name: "Jungle Fence",
        resolution: ItemModel::Block("block/jungle_fence_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 191,
        name: "Dark Oak Fence",
        resolution: ItemModel::Block("block/dark_oak_fence_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 192,
        name: "Acacia Fence",
        resolution: ItemModel::Block("block/acacia_fence_inventory"),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 256,
        name: "Iron Shovel",
        resolution: ItemModel::Generated(&["items/iron_shovel"]),
        max_stack: 1,
        max_damage: 250,
        attributes: ItemAttributes {
            attack_damage: Some(3.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 257,
        name: "Iron Pickaxe",
        resolution: ItemModel::Generated(&["items/iron_pickaxe"]),
        max_stack: 1,
        max_damage: 250,
        attributes: ItemAttributes {
            attack_damage: Some(4.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 258,
        name: "Iron Axe",
        resolution: ItemModel::Generated(&["items/iron_axe"]),
        max_stack: 1,
        max_damage: 250,
        attributes: ItemAttributes {
            attack_damage: Some(5.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 259,
        name: "Flint and Steel",
        resolution: ItemModel::Generated(&["items/flint_and_steel"]),
        max_stack: 1,
        max_damage: 64,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 260,
        name: "Apple",
        resolution: ItemModel::Generated(&["items/apple"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 261,
        name: "Bow",
        resolution: ItemModel::Generated(&["items/bow_standby"]),
        max_stack: 1,
        max_damage: 384,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 262,
        name: "Arrow",
        resolution: ItemModel::Generated(&["items/arrow"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 263,
        name: "Coal",
        resolution: ItemModel::Generated(&["items/coal"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 264,
        name: "Diamond",
        resolution: ItemModel::Generated(&["items/diamond"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 265,
        name: "Iron Ingot",
        resolution: ItemModel::Generated(&["items/iron_ingot"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 266,
        name: "Gold Ingot",
        resolution: ItemModel::Generated(&["items/gold_ingot"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 267,
        name: "Iron Sword",
        resolution: ItemModel::Generated(&["items/iron_sword"]),
        max_stack: 1,
        max_damage: 250,
        attributes: ItemAttributes {
            attack_damage: Some(6.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 268,
        name: "Wooden Sword",
        resolution: ItemModel::Generated(&["items/wood_sword"]),
        max_stack: 1,
        max_damage: 59,
        attributes: ItemAttributes {
            attack_damage: Some(4.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 269,
        name: "Wooden Shovel",
        resolution: ItemModel::Generated(&["items/wood_shovel"]),
        max_stack: 1,
        max_damage: 59,
        attributes: ItemAttributes {
            attack_damage: Some(1.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 270,
        name: "Wooden Pickaxe",
        resolution: ItemModel::Generated(&["items/wood_pickaxe"]),
        max_stack: 1,
        max_damage: 59,
        attributes: ItemAttributes {
            attack_damage: Some(2.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 271,
        name: "Wooden Axe",
        resolution: ItemModel::Generated(&["items/wood_axe"]),
        max_stack: 1,
        max_damage: 59,
        attributes: ItemAttributes {
            attack_damage: Some(3.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 272,
        name: "Stone Sword",
        resolution: ItemModel::Generated(&["items/stone_sword"]),
        max_stack: 1,
        max_damage: 131,
        attributes: ItemAttributes {
            attack_damage: Some(5.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 273,
        name: "Stone Shovel",
        resolution: ItemModel::Generated(&["items/stone_shovel"]),
        max_stack: 1,
        max_damage: 131,
        attributes: ItemAttributes {
            attack_damage: Some(2.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 274,
        name: "Stone Pickaxe",
        resolution: ItemModel::Generated(&["items/stone_pickaxe"]),
        max_stack: 1,
        max_damage: 131,
        attributes: ItemAttributes {
            attack_damage: Some(3.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 275,
        name: "Stone Axe",
        resolution: ItemModel::Generated(&["items/stone_axe"]),
        max_stack: 1,
        max_damage: 131,
        attributes: ItemAttributes {
            attack_damage: Some(4.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 276,
        name: "Diamond Sword",
        resolution: ItemModel::Generated(&["items/diamond_sword"]),
        max_stack: 1,
        max_damage: 1561,
        attributes: ItemAttributes {
            attack_damage: Some(7.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 277,
        name: "Diamond Shovel",
        resolution: ItemModel::Generated(&["items/diamond_shovel"]),
        max_stack: 1,
        max_damage: 1561,
        attributes: ItemAttributes {
            attack_damage: Some(4.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 278,
        name: "Diamond Pickaxe",
        resolution: ItemModel::Generated(&["items/diamond_pickaxe"]),
        max_stack: 1,
        max_damage: 1561,
        attributes: ItemAttributes {
            attack_damage: Some(5.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 279,
        name: "Diamond Axe",
        resolution: ItemModel::Generated(&["items/diamond_axe"]),
        max_stack: 1,
        max_damage: 1561,
        attributes: ItemAttributes {
            attack_damage: Some(6.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 280,
        name: "Stick",
        resolution: ItemModel::Generated(&["items/stick"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 281,
        name: "Bowl",
        resolution: ItemModel::Generated(&["items/bowl"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 282,
        name: "Mushroom Stew",
        resolution: ItemModel::Generated(&["items/mushroom_stew"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 283,
        name: "Golden Sword",
        resolution: ItemModel::Generated(&["items/gold_sword"]),
        max_stack: 1,
        max_damage: 32,
        attributes: ItemAttributes {
            attack_damage: Some(4.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 284,
        name: "Golden Shovel",
        resolution: ItemModel::Generated(&["items/gold_shovel"]),
        max_stack: 1,
        max_damage: 32,
        attributes: ItemAttributes {
            attack_damage: Some(1.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 285,
        name: "Golden Pickaxe",
        resolution: ItemModel::Generated(&["items/gold_pickaxe"]),
        max_stack: 1,
        max_damage: 32,
        attributes: ItemAttributes {
            attack_damage: Some(2.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 286,
        name: "Golden Axe",
        resolution: ItemModel::Generated(&["items/gold_axe"]),
        max_stack: 1,
        max_damage: 32,
        attributes: ItemAttributes {
            attack_damage: Some(3.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 287,
        name: "String",
        resolution: ItemModel::Generated(&["items/string"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 288,
        name: "Feather",
        resolution: ItemModel::Generated(&["items/feather"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 289,
        name: "Gunpowder",
        resolution: ItemModel::Generated(&["items/gunpowder"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 290,
        name: "Wooden Hoe",
        resolution: ItemModel::Generated(&["items/wood_hoe"]),
        max_stack: 1,
        max_damage: 59,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 291,
        name: "Stone Hoe",
        resolution: ItemModel::Generated(&["items/stone_hoe"]),
        max_stack: 1,
        max_damage: 131,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 292,
        name: "Iron Hoe",
        resolution: ItemModel::Generated(&["items/iron_hoe"]),
        max_stack: 1,
        max_damage: 250,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 293,
        name: "Diamond Hoe",
        resolution: ItemModel::Generated(&["items/diamond_hoe"]),
        max_stack: 1,
        max_damage: 1561,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 294,
        name: "Golden Hoe",
        resolution: ItemModel::Generated(&["items/gold_hoe"]),
        max_stack: 1,
        max_damage: 32,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 295,
        name: "Seeds",
        resolution: ItemModel::Generated(&["items/seeds_wheat"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 296,
        name: "Wheat",
        resolution: ItemModel::Generated(&["items/wheat"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 297,
        name: "Bread",
        resolution: ItemModel::Generated(&["items/bread"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 298,
        name: "Leather Cap",
        resolution: ItemModel::Generated(&["items/leather_helmet", "items/leather_helmet_overlay"]),
        max_stack: 1,
        max_damage: 55,
        attributes: ItemAttributes {
            armour_points: Some(1.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 299,
        name: "Leather Tunic",
        resolution: ItemModel::Generated(&[
            "items/leather_chestplate",
            "items/leather_chestplate_overlay",
        ]),
        max_stack: 1,
        max_damage: 80,
        attributes: ItemAttributes {
            armour_points: Some(3.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 300,
        name: "Leather Pants",
        resolution: ItemModel::Generated(&[
            "items/leather_leggings",
            "items/leather_leggings_overlay",
        ]),
        max_stack: 1,
        max_damage: 75,
        attributes: ItemAttributes {
            armour_points: Some(2.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 301,
        name: "Leather Boots",
        resolution: ItemModel::Generated(&["items/leather_boots", "items/leather_boots_overlay"]),
        max_stack: 1,
        max_damage: 65,
        attributes: ItemAttributes {
            armour_points: Some(1.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 302,
        name: "Chain Helmet",
        resolution: ItemModel::Generated(&["items/chainmail_helmet"]),
        max_stack: 1,
        max_damage: 165,
        attributes: ItemAttributes {
            armour_points: Some(2.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 303,
        name: "Chain Chestplate",
        resolution: ItemModel::Generated(&["items/chainmail_chestplate"]),
        max_stack: 1,
        max_damage: 240,
        attributes: ItemAttributes {
            armour_points: Some(5.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 304,
        name: "Chain Leggings",
        resolution: ItemModel::Generated(&["items/chainmail_leggings"]),
        max_stack: 1,
        max_damage: 225,
        attributes: ItemAttributes {
            armour_points: Some(4.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 305,
        name: "Chain Boots",
        resolution: ItemModel::Generated(&["items/chainmail_boots"]),
        max_stack: 1,
        max_damage: 195,
        attributes: ItemAttributes {
            armour_points: Some(1.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 306,
        name: "Iron Helmet",
        resolution: ItemModel::Generated(&["items/iron_helmet"]),
        max_stack: 1,
        max_damage: 165,
        attributes: ItemAttributes {
            armour_points: Some(2.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 307,
        name: "Iron Chestplate",
        resolution: ItemModel::Generated(&["items/iron_chestplate"]),
        max_stack: 1,
        max_damage: 240,
        attributes: ItemAttributes {
            armour_points: Some(6.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 308,
        name: "Iron Leggings",
        resolution: ItemModel::Generated(&["items/iron_leggings"]),
        max_stack: 1,
        max_damage: 225,
        attributes: ItemAttributes {
            armour_points: Some(5.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 309,
        name: "Iron Boots",
        resolution: ItemModel::Generated(&["items/iron_boots"]),
        max_stack: 1,
        max_damage: 195,
        attributes: ItemAttributes {
            armour_points: Some(2.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 310,
        name: "Diamond Helmet",
        resolution: ItemModel::Generated(&["items/diamond_helmet"]),
        max_stack: 1,
        max_damage: 363,
        attributes: ItemAttributes {
            armour_points: Some(3.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 311,
        name: "Diamond Chestplate",
        resolution: ItemModel::Generated(&["items/diamond_chestplate"]),
        max_stack: 1,
        max_damage: 528,
        attributes: ItemAttributes {
            armour_points: Some(8.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 312,
        name: "Diamond Leggings",
        resolution: ItemModel::Generated(&["items/diamond_leggings"]),
        max_stack: 1,
        max_damage: 495,
        attributes: ItemAttributes {
            armour_points: Some(6.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 313,
        name: "Diamond Boots",
        resolution: ItemModel::Generated(&["items/diamond_boots"]),
        max_stack: 1,
        max_damage: 429,
        attributes: ItemAttributes {
            armour_points: Some(3.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 314,
        name: "Golden Helmet",
        resolution: ItemModel::Generated(&["items/gold_helmet"]),
        max_stack: 1,
        max_damage: 77,
        attributes: ItemAttributes {
            armour_points: Some(2.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 315,
        name: "Golden Chestplate",
        resolution: ItemModel::Generated(&["items/gold_chestplate"]),
        max_stack: 1,
        max_damage: 112,
        attributes: ItemAttributes {
            armour_points: Some(5.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 316,
        name: "Golden Leggings",
        resolution: ItemModel::Generated(&["items/gold_leggings"]),
        max_stack: 1,
        max_damage: 105,
        attributes: ItemAttributes {
            armour_points: Some(3.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 317,
        name: "Golden Boots",
        resolution: ItemModel::Generated(&["items/gold_boots"]),
        max_stack: 1,
        max_damage: 91,
        attributes: ItemAttributes {
            armour_points: Some(1.0),
            ..ItemAttributes::NONE
        },
        variants: false,
    },
    ItemEntry {
        id: 318,
        name: "Flint",
        resolution: ItemModel::Generated(&["items/flint"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 319,
        name: "Raw Porkchop",
        resolution: ItemModel::Generated(&["items/porkchop_raw"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 320,
        name: "Cooked Porkchop",
        resolution: ItemModel::Generated(&["items/porkchop_cooked"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 321,
        name: "Painting",
        resolution: ItemModel::Generated(&["items/painting"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 322,
        name: "Golden Apple",
        resolution: ItemModel::Generated(&["items/apple_golden"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 323,
        name: "Sign",
        resolution: ItemModel::Generated(&["items/sign"]),
        max_stack: 16,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 324,
        name: "Oak Door",
        resolution: ItemModel::Generated(&["items/door_wood"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 325,
        name: "Bucket",
        resolution: ItemModel::Generated(&["items/bucket_empty"]),
        max_stack: 16,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 326,
        name: "Water Bucket",
        resolution: ItemModel::Generated(&["items/bucket_water"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 327,
        name: "Lava Bucket",
        resolution: ItemModel::Generated(&["items/bucket_lava"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 328,
        name: "Minecart",
        resolution: ItemModel::Generated(&["items/minecart_normal"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 329,
        name: "Saddle",
        resolution: ItemModel::Generated(&["items/saddle"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 330,
        name: "Iron Door",
        resolution: ItemModel::Generated(&["items/door_iron"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 331,
        name: "Redstone",
        resolution: ItemModel::Generated(&["items/redstone_dust"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 332,
        name: "Snowball",
        resolution: ItemModel::Generated(&["items/snowball"]),
        max_stack: 16,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 333,
        name: "Boat",
        resolution: ItemModel::Generated(&["items/boat"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 334,
        name: "Leather",
        resolution: ItemModel::Generated(&["items/leather"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 335,
        name: "Milk",
        resolution: ItemModel::Generated(&["items/bucket_milk"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 336,
        name: "Brick",
        resolution: ItemModel::Generated(&["items/brick"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 337,
        name: "Clay",
        resolution: ItemModel::Generated(&["items/clay_ball"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 338,
        name: "Sugar Canes",
        resolution: ItemModel::Generated(&["items/reeds"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 339,
        name: "Paper",
        resolution: ItemModel::Generated(&["items/paper"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 340,
        name: "Book",
        resolution: ItemModel::Generated(&["items/book_normal"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 341,
        name: "Slimeball",
        resolution: ItemModel::Generated(&["items/slimeball"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 342,
        name: "Minecart with Chest",
        resolution: ItemModel::Generated(&["items/minecart_chest"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 343,
        name: "Minecart with Furnace",
        resolution: ItemModel::Generated(&["items/minecart_furnace"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 344,
        name: "Egg",
        resolution: ItemModel::Generated(&["items/egg"]),
        max_stack: 16,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 345,
        name: "Compass",
        resolution: ItemModel::Missing,
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 346,
        name: "Fishing Rod",
        resolution: ItemModel::Generated(&["items/fishing_rod_uncast"]),
        max_stack: 1,
        max_damage: 64,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 347,
        name: "Clock",
        resolution: ItemModel::Missing,
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 348,
        name: "Glowstone Dust",
        resolution: ItemModel::Generated(&["items/glowstone_dust"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 349,
        name: "Raw Fish",
        resolution: ItemModel::Generated(&["items/fish_cod_raw"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 350,
        name: "Cooked Fish",
        resolution: ItemModel::Generated(&["items/fish_cod_cooked"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 351,
        name: "Ink Sac",
        resolution: ItemModel::Generated(&["items/dye_powder_black"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 352,
        name: "Bone",
        resolution: ItemModel::Generated(&["items/bone"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 353,
        name: "Sugar",
        resolution: ItemModel::Generated(&["items/sugar"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 354,
        name: "Cake",
        resolution: ItemModel::Generated(&["items/cake"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 355,
        name: "Bed",
        resolution: ItemModel::Generated(&["items/bed"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 356,
        name: "Redstone Repeater",
        resolution: ItemModel::Generated(&["items/repeater"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 357,
        name: "Cookie",
        resolution: ItemModel::Generated(&["items/cookie"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 358,
        name: "Map",
        resolution: ItemModel::Generated(&["items/map_filled"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 359,
        name: "Shears",
        resolution: ItemModel::Generated(&["items/shears"]),
        max_stack: 1,
        max_damage: 238,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 360,
        name: "Melon",
        resolution: ItemModel::Generated(&["items/melon"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 361,
        name: "Pumpkin Seeds",
        resolution: ItemModel::Generated(&["items/seeds_pumpkin"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 362,
        name: "Melon Seeds",
        resolution: ItemModel::Generated(&["items/seeds_melon"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 363,
        name: "Raw Beef",
        resolution: ItemModel::Generated(&["items/beef_raw"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 364,
        name: "Steak",
        resolution: ItemModel::Generated(&["items/beef_cooked"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 365,
        name: "Raw Chicken",
        resolution: ItemModel::Generated(&["items/chicken_raw"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 366,
        name: "Cooked Chicken",
        resolution: ItemModel::Generated(&["items/chicken_cooked"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 367,
        name: "Rotten Flesh",
        resolution: ItemModel::Generated(&["items/rotten_flesh"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 368,
        name: "Ender Pearl",
        resolution: ItemModel::Generated(&["items/ender_pearl"]),
        max_stack: 16,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 369,
        name: "Blaze Rod",
        resolution: ItemModel::Generated(&["items/blaze_rod"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 370,
        name: "Ghast Tear",
        resolution: ItemModel::Generated(&["items/ghast_tear"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 371,
        name: "Gold Nugget",
        resolution: ItemModel::Generated(&["items/gold_nugget"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 372,
        name: "Nether Wart",
        resolution: ItemModel::Generated(&["items/nether_wart"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 373,
        name: "Water Bottle",
        resolution: ItemModel::Generated(&[
            "items/potion_overlay",
            "items/potion_bottle_drinkable",
        ]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 374,
        name: "Glass Bottle",
        resolution: ItemModel::Generated(&["items/potion_bottle_empty"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 375,
        name: "Spider Eye",
        resolution: ItemModel::Generated(&["items/spider_eye"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 376,
        name: "Fermented Spider Eye",
        resolution: ItemModel::Generated(&["items/spider_eye_fermented"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 377,
        name: "Blaze Powder",
        resolution: ItemModel::Generated(&["items/blaze_powder"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 378,
        name: "Magma Cream",
        resolution: ItemModel::Generated(&["items/magma_cream"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 379,
        name: "Brewing Stand",
        resolution: ItemModel::Generated(&["items/brewing_stand"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 380,
        name: "Cauldron",
        resolution: ItemModel::Generated(&["items/cauldron"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 381,
        name: "Eye of Ender",
        resolution: ItemModel::Generated(&["items/ender_eye"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 382,
        name: "Glistering Melon",
        resolution: ItemModel::Generated(&["items/melon_speckled"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 383,
        name: "Spawn",
        resolution: ItemModel::Generated(&["items/spawn_egg", "items/spawn_egg_overlay"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 384,
        name: "Bottle o' Enchanting",
        resolution: ItemModel::Generated(&["items/experience_bottle"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 385,
        name: "Fire Charge",
        resolution: ItemModel::Generated(&["items/fireball"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 386,
        name: "Book and Quill",
        resolution: ItemModel::Generated(&["items/book_writable"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 387,
        name: "Written Book",
        resolution: ItemModel::Generated(&["items/book_written"]),
        max_stack: 16,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 388,
        name: "Emerald",
        resolution: ItemModel::Generated(&["items/emerald"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 389,
        name: "Item Frame",
        resolution: ItemModel::Generated(&["items/item_frame"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 390,
        name: "Flower Pot",
        resolution: ItemModel::Generated(&["items/flower_pot"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 391,
        name: "Carrot",
        resolution: ItemModel::Generated(&["items/carrot"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 392,
        name: "Potato",
        resolution: ItemModel::Generated(&["items/potato"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 393,
        name: "Baked Potato",
        resolution: ItemModel::Generated(&["items/potato_baked"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 394,
        name: "Poisonous Potato",
        resolution: ItemModel::Generated(&["items/potato_poisonous"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 395,
        name: "Empty Map",
        resolution: ItemModel::Generated(&["items/map_empty"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 396,
        name: "Golden Carrot",
        resolution: ItemModel::Generated(&["items/carrot_golden"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 397,
        name: "Skeleton Skull",
        resolution: ItemModel::Missing,
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 398,
        name: "Carrot on a Stick",
        resolution: ItemModel::Generated(&["items/carrot_on_a_stick"]),
        max_stack: 1,
        max_damage: 25,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 399,
        name: "Nether Star",
        resolution: ItemModel::Generated(&["items/nether_star"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 400,
        name: "Pumpkin Pie",
        resolution: ItemModel::Generated(&["items/pumpkin_pie"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 401,
        name: "Firework Rocket",
        resolution: ItemModel::Generated(&["items/fireworks"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 402,
        name: "Firework Star",
        resolution: ItemModel::Generated(&[
            "items/fireworks_charge",
            "items/fireworks_charge_overlay",
        ]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 403,
        name: "Enchanted Book",
        resolution: ItemModel::Generated(&["items/book_enchanted"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 404,
        name: "Redstone Comparator",
        resolution: ItemModel::Generated(&["items/comparator"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 405,
        name: "Nether Brick",
        resolution: ItemModel::Generated(&["items/netherbrick"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 406,
        name: "Nether Quartz",
        resolution: ItemModel::Generated(&["items/quartz"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 407,
        name: "Minecart with TNT",
        resolution: ItemModel::Generated(&["items/minecart_tnt"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 408,
        name: "Minecart with Hopper",
        resolution: ItemModel::Generated(&["items/minecart_hopper"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 409,
        name: "Prismarine Shard",
        resolution: ItemModel::Generated(&["items/prismarine_shard"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 410,
        name: "Prismarine Crystals",
        resolution: ItemModel::Generated(&["items/prismarine_crystals"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 411,
        name: "Raw Rabbit",
        resolution: ItemModel::Generated(&["items/rabbit_raw"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 412,
        name: "Cooked Rabbit",
        resolution: ItemModel::Generated(&["items/rabbit_cooked"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 413,
        name: "Rabbit Stew",
        resolution: ItemModel::Generated(&["items/rabbit_stew"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 414,
        name: "Rabbit's Foot",
        resolution: ItemModel::Generated(&["items/rabbit_foot"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 415,
        name: "Rabbit Hide",
        resolution: ItemModel::Generated(&["items/rabbit_hide"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 416,
        name: "Armor Stand",
        resolution: ItemModel::Generated(&["items/wooden_armorstand"]),
        max_stack: 16,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 417,
        name: "Iron Horse Armor",
        resolution: ItemModel::Generated(&["items/iron_horse_armor"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 418,
        name: "Gold Horse Armor",
        resolution: ItemModel::Generated(&["items/gold_horse_armor"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 419,
        name: "Diamond Horse Armor",
        resolution: ItemModel::Generated(&["items/diamond_horse_armor"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 420,
        name: "Lead",
        resolution: ItemModel::Generated(&["items/lead"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 421,
        name: "Name Tag",
        resolution: ItemModel::Generated(&["items/name_tag"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 422,
        name: "Minecart with Command Block",
        resolution: ItemModel::Generated(&["items/minecart_command_block"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 423,
        name: "Raw Mutton",
        resolution: ItemModel::Generated(&["items/mutton_raw"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 424,
        name: "Cooked Mutton",
        resolution: ItemModel::Generated(&["items/mutton_cooked"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 425,
        name: "Black Banner",
        resolution: ItemModel::Missing,
        max_stack: 16,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: true,
    },
    ItemEntry {
        id: 427,
        name: "Spruce Door",
        resolution: ItemModel::Generated(&["items/door_spruce"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 428,
        name: "Birch Door",
        resolution: ItemModel::Generated(&["items/door_birch"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 429,
        name: "Jungle Door",
        resolution: ItemModel::Generated(&["items/door_jungle"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 430,
        name: "Acacia Door",
        resolution: ItemModel::Generated(&["items/door_acacia"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 431,
        name: "Dark Oak Door",
        resolution: ItemModel::Generated(&["items/door_dark_oak"]),
        max_stack: 64,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2256,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_13"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2257,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_cat"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2258,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_blocks"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2259,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_chirp"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2260,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_far"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2261,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_mall"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2262,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_mellohi"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2263,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_stal"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2264,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_strad"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2265,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_ward"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2266,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_11"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
    ItemEntry {
        id: 2267,
        name: "Music Disc",
        resolution: ItemModel::Generated(&["items/record_wait"]),
        max_stack: 1,
        max_damage: 0,
        attributes: ItemAttributes::NONE,
        variants: false,
    },
];
