[package]
name = "oxide-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
flate2 = { version = "1", features = ["zlib-ng-compat"] }
