[package]
name = "oxide-proto-v47"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
oxide-proto = { path = "../oxide-proto" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
