[package]
name = "oxide-game"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
oxide-proto-v47.workspace = true
oxide-render.workspace = true
oxide-world.workspace = true
thiserror.workspace = true
