[package]
name = "oxide-launcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "oxide-launcher"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
oxide-proto-v47.workspace = true
thiserror.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing-subscriber.workspace = true
